// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: handle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// # Safety
// The foreign language is responsable for disposing handles
// Forgetting to dispose the handle may lead to memory leaks
//
// Dropping a handle doesn't necessarily mean that the object is destroyed if it is still used
// on the FfiServer (Atomic reference counting)
//
// When refering to a handle without owning it, we just use a uint32 without this message.
// (the variable name is suffixed with "_handle")
type FfiOwnedHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FfiOwnedHandle) Reset() {
	*x = FfiOwnedHandle{}
	mi := &file_handle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FfiOwnedHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FfiOwnedHandle) ProtoMessage() {}

func (x *FfiOwnedHandle) ProtoReflect() protoreflect.Message {
	mi := &file_handle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FfiOwnedHandle.ProtoReflect.Descriptor instead.
func (*FfiOwnedHandle) Descriptor() ([]byte, []int) {
	return file_handle_proto_rawDescGZIP(), []int{0}
}

func (x *FfiOwnedHandle) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

var File_handle_proto protoreflect.FileDescriptor

const file_handle_proto_rawDesc = "" +
	"\n" +
	"\fhandle.proto\x12\rlivekit.proto\" \n" +
	"\x0eFfiOwnedHandle\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x04R\x02idB\x19Z\a./proto\xaa\x02\rLiveKit.Proto"

var (
	file_handle_proto_rawDescOnce sync.Once
	file_handle_proto_rawDescData []byte
)

func file_handle_proto_rawDescGZIP() []byte {
	file_handle_proto_rawDescOnce.Do(func() {
		file_handle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_handle_proto_rawDesc), len(file_handle_proto_rawDesc)))
	})
	return file_handle_proto_rawDescData
}

var file_handle_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_handle_proto_goTypes = []any{
	(*FfiOwnedHandle)(nil), // 0: livekit.proto.FfiOwnedHandle
}
var file_handle_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_handle_proto_init() }
func file_handle_proto_init() {
	if File_handle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_handle_proto_rawDesc), len(file_handle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_handle_proto_goTypes,
		DependencyIndexes: file_handle_proto_depIdxs,
		MessageInfos:      file_handle_proto_msgTypes,
	}.Build()
	File_handle_proto = out.File
	file_handle_proto_goTypes = nil
	file_handle_proto_depIdxs = nil
}
