// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: participant.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParticipantKind int32

const (
	ParticipantKind_PARTICIPANT_KIND_STANDARD ParticipantKind = 0
	ParticipantKind_PARTICIPANT_KIND_INGRESS  ParticipantKind = 1
	ParticipantKind_PARTICIPANT_KIND_EGRESS   ParticipantKind = 2
	ParticipantKind_PARTICIPANT_KIND_SIP      ParticipantKind = 3
	ParticipantKind_PARTICIPANT_KIND_AGENT    ParticipantKind = 4
)

// Enum value maps for ParticipantKind.
var (
	ParticipantKind_name = map[int32]string{
		0: "PARTICIPANT_KIND_STANDARD",
		1: "PARTICIPANT_KIND_INGRESS",
		2: "PARTICIPANT_KIND_EGRESS",
		3: "PARTICIPANT_KIND_SIP",
		4: "PARTICIPANT_KIND_AGENT",
	}
	ParticipantKind_value = map[string]int32{
		"PARTICIPANT_KIND_STANDARD": 0,
		"PARTICIPANT_KIND_INGRESS":  1,
		"PARTICIPANT_KIND_EGRESS":   2,
		"PARTICIPANT_KIND_SIP":      3,
		"PARTICIPANT_KIND_AGENT":    4,
	}
)

func (x ParticipantKind) Enum() *ParticipantKind {
	p := new(ParticipantKind)
	*p = x
	return p
}

func (x ParticipantKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParticipantKind) Descriptor() protoreflect.EnumDescriptor {
	return file_participant_proto_enumTypes[0].Descriptor()
}

func (ParticipantKind) Type() protoreflect.EnumType {
	return &file_participant_proto_enumTypes[0]
}

func (x ParticipantKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ParticipantKind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ParticipantKind(num)
	return nil
}

// Deprecated: Use ParticipantKind.Descriptor instead.
func (ParticipantKind) EnumDescriptor() ([]byte, []int) {
	return file_participant_proto_rawDescGZIP(), []int{0}
}

type DisconnectReason int32

const (
	DisconnectReason_UNKNOWN_REASON DisconnectReason = 0
	// the client initiated the disconnect
	DisconnectReason_CLIENT_INITIATED DisconnectReason = 1
	// another participant with the same identity has joined the room
	DisconnectReason_DUPLICATE_IDENTITY DisconnectReason = 2
	// the server instance is shutting down
	DisconnectReason_SERVER_SHUTDOWN DisconnectReason = 3
	// RoomService.RemoveParticipant was called
	DisconnectReason_PARTICIPANT_REMOVED DisconnectReason = 4
	// RoomService.DeleteRoom was called
	DisconnectReason_ROOM_DELETED DisconnectReason = 5
	// the client is attempting to resume a session, but server is not aware of it
	DisconnectReason_STATE_MISMATCH DisconnectReason = 6
	// client was unable to connect fully
	DisconnectReason_JOIN_FAILURE DisconnectReason = 7
	// Cloud-only, the server requested Participant to migrate the connection elsewhere
	DisconnectReason_MIGRATION DisconnectReason = 8
	// the signal websocket was closed unexpectedly
	DisconnectReason_SIGNAL_CLOSE DisconnectReason = 9
	// the room was closed, due to all Standard and Ingress participants having left
	DisconnectReason_ROOM_CLOSED DisconnectReason = 10
	// SIP callee did not respond in time
	DisconnectReason_USER_UNAVAILABLE DisconnectReason = 11
	// SIP callee rejected the call (busy)
	DisconnectReason_USER_REJECTED DisconnectReason = 12
	// SIP protocol failure or unexpected response
	DisconnectReason_SIP_TRUNK_FAILURE  DisconnectReason = 13
	DisconnectReason_CONNECTION_TIMEOUT DisconnectReason = 14
	DisconnectReason_MEDIA_FAILURE      DisconnectReason = 15
)

// Enum value maps for DisconnectReason.
var (
	DisconnectReason_name = map[int32]string{
		0:  "UNKNOWN_REASON",
		1:  "CLIENT_INITIATED",
		2:  "DUPLICATE_IDENTITY",
		3:  "SERVER_SHUTDOWN",
		4:  "PARTICIPANT_REMOVED",
		5:  "ROOM_DELETED",
		6:  "STATE_MISMATCH",
		7:  "JOIN_FAILURE",
		8:  "MIGRATION",
		9:  "SIGNAL_CLOSE",
		10: "ROOM_CLOSED",
		11: "USER_UNAVAILABLE",
		12: "USER_REJECTED",
		13: "SIP_TRUNK_FAILURE",
		14: "CONNECTION_TIMEOUT",
		15: "MEDIA_FAILURE",
	}
	DisconnectReason_value = map[string]int32{
		"UNKNOWN_REASON":      0,
		"CLIENT_INITIATED":    1,
		"DUPLICATE_IDENTITY":  2,
		"SERVER_SHUTDOWN":     3,
		"PARTICIPANT_REMOVED": 4,
		"ROOM_DELETED":        5,
		"STATE_MISMATCH":      6,
		"JOIN_FAILURE":        7,
		"MIGRATION":           8,
		"SIGNAL_CLOSE":        9,
		"ROOM_CLOSED":         10,
		"USER_UNAVAILABLE":    11,
		"USER_REJECTED":       12,
		"SIP_TRUNK_FAILURE":   13,
		"CONNECTION_TIMEOUT":  14,
		"MEDIA_FAILURE":       15,
	}
)

func (x DisconnectReason) Enum() *DisconnectReason {
	p := new(DisconnectReason)
	*p = x
	return p
}

func (x DisconnectReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisconnectReason) Descriptor() protoreflect.EnumDescriptor {
	return file_participant_proto_enumTypes[1].Descriptor()
}

func (DisconnectReason) Type() protoreflect.EnumType {
	return &file_participant_proto_enumTypes[1]
}

func (x DisconnectReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DisconnectReason) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DisconnectReason(num)
	return nil
}

// Deprecated: Use DisconnectReason.Descriptor instead.
func (DisconnectReason) EnumDescriptor() ([]byte, []int) {
	return file_participant_proto_rawDescGZIP(), []int{1}
}

type ParticipantInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Sid              *string                `protobuf:"bytes,1,req,name=sid" json:"sid,omitempty"`
	Name             *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Identity         *string                `protobuf:"bytes,3,req,name=identity" json:"identity,omitempty"`
	Metadata         *string                `protobuf:"bytes,4,req,name=metadata" json:"metadata,omitempty"`
	Attributes       map[string]string      `protobuf:"bytes,5,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Kind             *ParticipantKind       `protobuf:"varint,6,req,name=kind,enum=livekit.proto.ParticipantKind" json:"kind,omitempty"`
	DisconnectReason *DisconnectReason      `protobuf:"varint,7,req,name=disconnect_reason,json=disconnectReason,enum=livekit.proto.DisconnectReason" json:"disconnect_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ParticipantInfo) Reset() {
	*x = ParticipantInfo{}
	mi := &file_participant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantInfo) ProtoMessage() {}

func (x *ParticipantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_participant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantInfo.ProtoReflect.Descriptor instead.
func (*ParticipantInfo) Descriptor() ([]byte, []int) {
	return file_participant_proto_rawDescGZIP(), []int{0}
}

func (x *ParticipantInfo) GetSid() string {
	if x != nil && x.Sid != nil {
		return *x.Sid
	}
	return ""
}

func (x *ParticipantInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ParticipantInfo) GetIdentity() string {
	if x != nil && x.Identity != nil {
		return *x.Identity
	}
	return ""
}

func (x *ParticipantInfo) GetMetadata() string {
	if x != nil && x.Metadata != nil {
		return *x.Metadata
	}
	return ""
}

func (x *ParticipantInfo) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ParticipantInfo) GetKind() ParticipantKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ParticipantKind_PARTICIPANT_KIND_STANDARD
}

func (x *ParticipantInfo) GetDisconnectReason() DisconnectReason {
	if x != nil && x.DisconnectReason != nil {
		return *x.DisconnectReason
	}
	return DisconnectReason_UNKNOWN_REASON
}

type OwnedParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *FfiOwnedHandle        `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Info          *ParticipantInfo       `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedParticipant) Reset() {
	*x = OwnedParticipant{}
	mi := &file_participant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedParticipant) ProtoMessage() {}

func (x *OwnedParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_participant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedParticipant.ProtoReflect.Descriptor instead.
func (*OwnedParticipant) Descriptor() ([]byte, []int) {
	return file_participant_proto_rawDescGZIP(), []int{1}
}

func (x *OwnedParticipant) GetHandle() *FfiOwnedHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *OwnedParticipant) GetInfo() *ParticipantInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_participant_proto protoreflect.FileDescriptor

const file_participant_proto_rawDesc = "" +
	"\n" +
	"\x11participant.proto\x12\rlivekit.proto\x1a\fhandle.proto\"\x80\x03\n" +
	"\x0fParticipantInfo\x12\x10\n" +
	"\x03sid\x18\x01 \x02(\tR\x03sid\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12\x1a\n" +
	"\bidentity\x18\x03 \x02(\tR\bidentity\x12\x1a\n" +
	"\bmetadata\x18\x04 \x02(\tR\bmetadata\x12N\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2..livekit.proto.ParticipantInfo.AttributesEntryR\n" +
	"attributes\x122\n" +
	"\x04kind\x18\x06 \x02(\x0e2\x1e.livekit.proto.ParticipantKindR\x04kind\x12L\n" +
	"\x11disconnect_reason\x18\a \x02(\x0e2\x1f.livekit.proto.DisconnectReasonR\x10disconnectReason\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x10OwnedParticipant\x125\n" +
	"\x06handle\x18\x01 \x02(\v2\x1d.livekit.proto.FfiOwnedHandleR\x06handle\x122\n" +
	"\x04info\x18\x02 \x02(\v2\x1e.livekit.proto.ParticipantInfoR\x04info*\xa1\x01\n" +
	"\x0fParticipantKind\x12\x1d\n" +
	"\x19PARTICIPANT_KIND_STANDARD\x10\x00\x12\x1c\n" +
	"\x18PARTICIPANT_KIND_INGRESS\x10\x01\x12\x1b\n" +
	"\x17PARTICIPANT_KIND_EGRESS\x10\x02\x12\x18\n" +
	"\x14PARTICIPANT_KIND_SIP\x10\x03\x12\x1a\n" +
	"\x16PARTICIPANT_KIND_AGENT\x10\x04*\xd7\x02\n" +
	"\x10DisconnectReason\x12\x12\n" +
	"\x0eUNKNOWN_REASON\x10\x00\x12\x14\n" +
	"\x10CLIENT_INITIATED\x10\x01\x12\x16\n" +
	"\x12DUPLICATE_IDENTITY\x10\x02\x12\x13\n" +
	"\x0fSERVER_SHUTDOWN\x10\x03\x12\x17\n" +
	"\x13PARTICIPANT_REMOVED\x10\x04\x12\x10\n" +
	"\fROOM_DELETED\x10\x05\x12\x12\n" +
	"\x0eSTATE_MISMATCH\x10\x06\x12\x10\n" +
	"\fJOIN_FAILURE\x10\a\x12\r\n" +
	"\tMIGRATION\x10\b\x12\x10\n" +
	"\fSIGNAL_CLOSE\x10\t\x12\x0f\n" +
	"\vROOM_CLOSED\x10\n" +
	"\x12\x14\n" +
	"\x10USER_UNAVAILABLE\x10\v\x12\x11\n" +
	"\rUSER_REJECTED\x10\f\x12\x15\n" +
	"\x11SIP_TRUNK_FAILURE\x10\r\x12\x16\n" +
	"\x12CONNECTION_TIMEOUT\x10\x0e\x12\x11\n" +
	"\rMEDIA_FAILURE\x10\x0fB\x19Z\a./proto\xaa\x02\rLiveKit.Proto"

var (
	file_participant_proto_rawDescOnce sync.Once
	file_participant_proto_rawDescData []byte
)

func file_participant_proto_rawDescGZIP() []byte {
	file_participant_proto_rawDescOnce.Do(func() {
		file_participant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_participant_proto_rawDesc), len(file_participant_proto_rawDesc)))
	})
	return file_participant_proto_rawDescData
}

var file_participant_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_participant_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_participant_proto_goTypes = []any{
	(ParticipantKind)(0),     // 0: livekit.proto.ParticipantKind
	(DisconnectReason)(0),    // 1: livekit.proto.DisconnectReason
	(*ParticipantInfo)(nil),  // 2: livekit.proto.ParticipantInfo
	(*OwnedParticipant)(nil), // 3: livekit.proto.OwnedParticipant
	nil,                      // 4: livekit.proto.ParticipantInfo.AttributesEntry
	(*FfiOwnedHandle)(nil),   // 5: livekit.proto.FfiOwnedHandle
}
var file_participant_proto_depIdxs = []int32{
	4, // 0: livekit.proto.ParticipantInfo.attributes:type_name -> livekit.proto.ParticipantInfo.AttributesEntry
	0, // 1: livekit.proto.ParticipantInfo.kind:type_name -> livekit.proto.ParticipantKind
	1, // 2: livekit.proto.ParticipantInfo.disconnect_reason:type_name -> livekit.proto.DisconnectReason
	5, // 3: livekit.proto.OwnedParticipant.handle:type_name -> livekit.proto.FfiOwnedHandle
	2, // 4: livekit.proto.OwnedParticipant.info:type_name -> livekit.proto.ParticipantInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_participant_proto_init() }
func file_participant_proto_init() {
	if File_participant_proto != nil {
		return
	}
	file_handle_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_participant_proto_rawDesc), len(file_participant_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_participant_proto_goTypes,
		DependencyIndexes: file_participant_proto_depIdxs,
		EnumInfos:         file_participant_proto_enumTypes,
		MessageInfos:      file_participant_proto_msgTypes,
	}.Build()
	File_participant_proto = out.File
	file_participant_proto_goTypes = nil
	file_participant_proto_depIdxs = nil
}
