// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *uint32                `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Message       *string                `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	Data          *string                `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcError) Reset() {
	*x = RpcError{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcError) ProtoMessage() {}

func (x *RpcError) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcError.ProtoReflect.Descriptor instead.
func (*RpcError) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcError) GetCode() uint32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *RpcError) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *RpcError) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

// FFI Requests
type PerformRpcRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LocalParticipantHandle *uint64                `protobuf:"varint,1,req,name=local_participant_handle,json=localParticipantHandle" json:"local_participant_handle,omitempty"`
	DestinationIdentity    *string                `protobuf:"bytes,2,req,name=destination_identity,json=destinationIdentity" json:"destination_identity,omitempty"`
	Method                 *string                `protobuf:"bytes,3,req,name=method" json:"method,omitempty"`
	Payload                *string                `protobuf:"bytes,4,req,name=payload" json:"payload,omitempty"`
	ResponseTimeoutMs      *uint32                `protobuf:"varint,5,opt,name=response_timeout_ms,json=responseTimeoutMs" json:"response_timeout_ms,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PerformRpcRequest) Reset() {
	*x = PerformRpcRequest{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformRpcRequest) ProtoMessage() {}

func (x *PerformRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformRpcRequest.ProtoReflect.Descriptor instead.
func (*PerformRpcRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *PerformRpcRequest) GetLocalParticipantHandle() uint64 {
	if x != nil && x.LocalParticipantHandle != nil {
		return *x.LocalParticipantHandle
	}
	return 0
}

func (x *PerformRpcRequest) GetDestinationIdentity() string {
	if x != nil && x.DestinationIdentity != nil {
		return *x.DestinationIdentity
	}
	return ""
}

func (x *PerformRpcRequest) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

func (x *PerformRpcRequest) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

func (x *PerformRpcRequest) GetResponseTimeoutMs() uint32 {
	if x != nil && x.ResponseTimeoutMs != nil {
		return *x.ResponseTimeoutMs
	}
	return 0
}

type RegisterRpcMethodRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LocalParticipantHandle *uint64                `protobuf:"varint,1,req,name=local_participant_handle,json=localParticipantHandle" json:"local_participant_handle,omitempty"`
	Method                 *string                `protobuf:"bytes,2,req,name=method" json:"method,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterRpcMethodRequest) Reset() {
	*x = RegisterRpcMethodRequest{}
	mi := &file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRpcMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRpcMethodRequest) ProtoMessage() {}

func (x *RegisterRpcMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRpcMethodRequest.ProtoReflect.Descriptor instead.
func (*RegisterRpcMethodRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRpcMethodRequest) GetLocalParticipantHandle() uint64 {
	if x != nil && x.LocalParticipantHandle != nil {
		return *x.LocalParticipantHandle
	}
	return 0
}

func (x *RegisterRpcMethodRequest) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

type UnregisterRpcMethodRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LocalParticipantHandle *uint64                `protobuf:"varint,1,req,name=local_participant_handle,json=localParticipantHandle" json:"local_participant_handle,omitempty"`
	Method                 *string                `protobuf:"bytes,2,req,name=method" json:"method,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UnregisterRpcMethodRequest) Reset() {
	*x = UnregisterRpcMethodRequest{}
	mi := &file_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRpcMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRpcMethodRequest) ProtoMessage() {}

func (x *UnregisterRpcMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRpcMethodRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRpcMethodRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterRpcMethodRequest) GetLocalParticipantHandle() uint64 {
	if x != nil && x.LocalParticipantHandle != nil {
		return *x.LocalParticipantHandle
	}
	return 0
}

func (x *UnregisterRpcMethodRequest) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

type RpcMethodInvocationResponseRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LocalParticipantHandle *uint64                `protobuf:"varint,1,req,name=local_participant_handle,json=localParticipantHandle" json:"local_participant_handle,omitempty"`
	InvocationId           *uint64                `protobuf:"varint,2,req,name=invocation_id,json=invocationId" json:"invocation_id,omitempty"`
	Payload                *string                `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	Error                  *RpcError              `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RpcMethodInvocationResponseRequest) Reset() {
	*x = RpcMethodInvocationResponseRequest{}
	mi := &file_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcMethodInvocationResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMethodInvocationResponseRequest) ProtoMessage() {}

func (x *RpcMethodInvocationResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcMethodInvocationResponseRequest.ProtoReflect.Descriptor instead.
func (*RpcMethodInvocationResponseRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *RpcMethodInvocationResponseRequest) GetLocalParticipantHandle() uint64 {
	if x != nil && x.LocalParticipantHandle != nil {
		return *x.LocalParticipantHandle
	}
	return 0
}

func (x *RpcMethodInvocationResponseRequest) GetInvocationId() uint64 {
	if x != nil && x.InvocationId != nil {
		return *x.InvocationId
	}
	return 0
}

func (x *RpcMethodInvocationResponseRequest) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

func (x *RpcMethodInvocationResponseRequest) GetError() *RpcError {
	if x != nil {
		return x.Error
	}
	return nil
}

// FFI Responses
type PerformRpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsyncId       *uint64                `protobuf:"varint,1,req,name=async_id,json=asyncId" json:"async_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformRpcResponse) Reset() {
	*x = PerformRpcResponse{}
	mi := &file_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformRpcResponse) ProtoMessage() {}

func (x *PerformRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformRpcResponse.ProtoReflect.Descriptor instead.
func (*PerformRpcResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *PerformRpcResponse) GetAsyncId() uint64 {
	if x != nil && x.AsyncId != nil {
		return *x.AsyncId
	}
	return 0
}

type RegisterRpcMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRpcMethodResponse) Reset() {
	*x = RegisterRpcMethodResponse{}
	mi := &file_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRpcMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRpcMethodResponse) ProtoMessage() {}

func (x *RegisterRpcMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRpcMethodResponse.ProtoReflect.Descriptor instead.
func (*RegisterRpcMethodResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

type UnregisterRpcMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRpcMethodResponse) Reset() {
	*x = UnregisterRpcMethodResponse{}
	mi := &file_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRpcMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRpcMethodResponse) ProtoMessage() {}

func (x *UnregisterRpcMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRpcMethodResponse.ProtoReflect.Descriptor instead.
func (*UnregisterRpcMethodResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{7}
}

type RpcMethodInvocationResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcMethodInvocationResponseResponse) Reset() {
	*x = RpcMethodInvocationResponseResponse{}
	mi := &file_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcMethodInvocationResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMethodInvocationResponseResponse) ProtoMessage() {}

func (x *RpcMethodInvocationResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcMethodInvocationResponseResponse.ProtoReflect.Descriptor instead.
func (*RpcMethodInvocationResponseResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *RpcMethodInvocationResponseResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// FFI Callbacks
type PerformRpcCallback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsyncId       *uint64                `protobuf:"varint,1,req,name=async_id,json=asyncId" json:"async_id,omitempty"`
	Payload       *string                `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	Error         *RpcError              `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformRpcCallback) Reset() {
	*x = PerformRpcCallback{}
	mi := &file_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformRpcCallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformRpcCallback) ProtoMessage() {}

func (x *PerformRpcCallback) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformRpcCallback.ProtoReflect.Descriptor instead.
func (*PerformRpcCallback) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *PerformRpcCallback) GetAsyncId() uint64 {
	if x != nil && x.AsyncId != nil {
		return *x.AsyncId
	}
	return 0
}

func (x *PerformRpcCallback) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

func (x *PerformRpcCallback) GetError() *RpcError {
	if x != nil {
		return x.Error
	}
	return nil
}

// FFI Events
type RpcMethodInvocationEvent struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LocalParticipantHandle *uint64                `protobuf:"varint,1,req,name=local_participant_handle,json=localParticipantHandle" json:"local_participant_handle,omitempty"`
	InvocationId           *uint64                `protobuf:"varint,2,req,name=invocation_id,json=invocationId" json:"invocation_id,omitempty"`
	Method                 *string                `protobuf:"bytes,3,req,name=method" json:"method,omitempty"`
	RequestId              *string                `protobuf:"bytes,4,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	CallerIdentity         *string                `protobuf:"bytes,5,req,name=caller_identity,json=callerIdentity" json:"caller_identity,omitempty"`
	Payload                *string                `protobuf:"bytes,6,req,name=payload" json:"payload,omitempty"`
	ResponseTimeoutMs      *uint32                `protobuf:"varint,7,req,name=response_timeout_ms,json=responseTimeoutMs" json:"response_timeout_ms,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RpcMethodInvocationEvent) Reset() {
	*x = RpcMethodInvocationEvent{}
	mi := &file_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcMethodInvocationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMethodInvocationEvent) ProtoMessage() {}

func (x *RpcMethodInvocationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcMethodInvocationEvent.ProtoReflect.Descriptor instead.
func (*RpcMethodInvocationEvent) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *RpcMethodInvocationEvent) GetLocalParticipantHandle() uint64 {
	if x != nil && x.LocalParticipantHandle != nil {
		return *x.LocalParticipantHandle
	}
	return 0
}

func (x *RpcMethodInvocationEvent) GetInvocationId() uint64 {
	if x != nil && x.InvocationId != nil {
		return *x.InvocationId
	}
	return 0
}

func (x *RpcMethodInvocationEvent) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

func (x *RpcMethodInvocationEvent) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *RpcMethodInvocationEvent) GetCallerIdentity() string {
	if x != nil && x.CallerIdentity != nil {
		return *x.CallerIdentity
	}
	return ""
}

func (x *RpcMethodInvocationEvent) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

func (x *RpcMethodInvocationEvent) GetResponseTimeoutMs() uint32 {
	if x != nil && x.ResponseTimeoutMs != nil {
		return *x.ResponseTimeoutMs
	}
	return 0
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\rlivekit.proto\"L\n" +
	"\bRpcError\x12\x12\n" +
	"\x04code\x18\x01 \x02(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x02(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"\xe2\x01\n" +
	"\x11PerformRpcRequest\x128\n" +
	"\x18local_participant_handle\x18\x01 \x02(\x04R\x16localParticipantHandle\x121\n" +
	"\x14destination_identity\x18\x02 \x02(\tR\x13destinationIdentity\x12\x16\n" +
	"\x06method\x18\x03 \x02(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x04 \x02(\tR\apayload\x12.\n" +
	"\x13response_timeout_ms\x18\x05 \x01(\rR\x11responseTimeoutMs\"l\n" +
	"\x18RegisterRpcMethodRequest\x128\n" +
	"\x18local_participant_handle\x18\x01 \x02(\x04R\x16localParticipantHandle\x12\x16\n" +
	"\x06method\x18\x02 \x02(\tR\x06method\"n\n" +
	"\x1aUnregisterRpcMethodRequest\x128\n" +
	"\x18local_participant_handle\x18\x01 \x02(\x04R\x16localParticipantHandle\x12\x16\n" +
	"\x06method\x18\x02 \x02(\tR\x06method\"\xcc\x01\n" +
	"\"RpcMethodInvocationResponseRequest\x128\n" +
	"\x18local_participant_handle\x18\x01 \x02(\x04R\x16localParticipantHandle\x12#\n" +
	"\rinvocation_id\x18\x02 \x02(\x04R\finvocationId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x17.livekit.proto.RpcErrorR\x05error\"/\n" +
	"\x12PerformRpcResponse\x12\x19\n" +
	"\basync_id\x18\x01 \x02(\x04R\aasyncId\"\x1b\n" +
	"\x19RegisterRpcMethodResponse\"\x1d\n" +
	"\x1bUnregisterRpcMethodResponse\";\n" +
	"#RpcMethodInvocationResponseResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"x\n" +
	"\x12PerformRpcCallback\x12\x19\n" +
	"\basync_id\x18\x01 \x02(\x04R\aasyncId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x17.livekit.proto.RpcErrorR\x05error\"\xa3\x02\n" +
	"\x18RpcMethodInvocationEvent\x128\n" +
	"\x18local_participant_handle\x18\x01 \x02(\x04R\x16localParticipantHandle\x12#\n" +
	"\rinvocation_id\x18\x02 \x02(\x04R\finvocationId\x12\x16\n" +
	"\x06method\x18\x03 \x02(\tR\x06method\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x02(\tR\trequestId\x12'\n" +
	"\x0fcaller_identity\x18\x05 \x02(\tR\x0ecallerIdentity\x12\x18\n" +
	"\apayload\x18\x06 \x02(\tR\apayload\x12.\n" +
	"\x13response_timeout_ms\x18\a \x02(\rR\x11responseTimeoutMsB\x19Z\a./proto\xaa\x02\rLiveKit.Proto"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpc_proto_goTypes = []any{
	(*RpcError)(nil),                            // 0: livekit.proto.RpcError
	(*PerformRpcRequest)(nil),                   // 1: livekit.proto.PerformRpcRequest
	(*RegisterRpcMethodRequest)(nil),            // 2: livekit.proto.RegisterRpcMethodRequest
	(*UnregisterRpcMethodRequest)(nil),          // 3: livekit.proto.UnregisterRpcMethodRequest
	(*RpcMethodInvocationResponseRequest)(nil),  // 4: livekit.proto.RpcMethodInvocationResponseRequest
	(*PerformRpcResponse)(nil),                  // 5: livekit.proto.PerformRpcResponse
	(*RegisterRpcMethodResponse)(nil),           // 6: livekit.proto.RegisterRpcMethodResponse
	(*UnregisterRpcMethodResponse)(nil),         // 7: livekit.proto.UnregisterRpcMethodResponse
	(*RpcMethodInvocationResponseResponse)(nil), // 8: livekit.proto.RpcMethodInvocationResponseResponse
	(*PerformRpcCallback)(nil),                  // 9: livekit.proto.PerformRpcCallback
	(*RpcMethodInvocationEvent)(nil),            // 10: livekit.proto.RpcMethodInvocationEvent
}
var file_rpc_proto_depIdxs = []int32{
	0, // 0: livekit.proto.RpcMethodInvocationResponseRequest.error:type_name -> livekit.proto.RpcError
	0, // 1: livekit.proto.PerformRpcCallback.error:type_name -> livekit.proto.RpcError
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
