// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: track.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackKind int32

const (
	TrackKind_KIND_UNKNOWN TrackKind = 0
	TrackKind_KIND_AUDIO   TrackKind = 1
	TrackKind_KIND_VIDEO   TrackKind = 2
)

// Enum value maps for TrackKind.
var (
	TrackKind_name = map[int32]string{
		0: "KIND_UNKNOWN",
		1: "KIND_AUDIO",
		2: "KIND_VIDEO",
	}
	TrackKind_value = map[string]int32{
		"KIND_UNKNOWN": 0,
		"KIND_AUDIO":   1,
		"KIND_VIDEO":   2,
	}
)

func (x TrackKind) Enum() *TrackKind {
	p := new(TrackKind)
	*p = x
	return p
}

func (x TrackKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackKind) Descriptor() protoreflect.EnumDescriptor {
	return file_track_proto_enumTypes[0].Descriptor()
}

func (TrackKind) Type() protoreflect.EnumType {
	return &file_track_proto_enumTypes[0]
}

func (x TrackKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TrackKind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TrackKind(num)
	return nil
}

// Deprecated: Use TrackKind.Descriptor instead.
func (TrackKind) EnumDescriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{0}
}

type TrackSource int32

const (
	TrackSource_SOURCE_UNKNOWN           TrackSource = 0
	TrackSource_SOURCE_CAMERA            TrackSource = 1
	TrackSource_SOURCE_MICROPHONE        TrackSource = 2
	TrackSource_SOURCE_SCREENSHARE       TrackSource = 3
	TrackSource_SOURCE_SCREENSHARE_AUDIO TrackSource = 4
)

// Enum value maps for TrackSource.
var (
	TrackSource_name = map[int32]string{
		0: "SOURCE_UNKNOWN",
		1: "SOURCE_CAMERA",
		2: "SOURCE_MICROPHONE",
		3: "SOURCE_SCREENSHARE",
		4: "SOURCE_SCREENSHARE_AUDIO",
	}
	TrackSource_value = map[string]int32{
		"SOURCE_UNKNOWN":           0,
		"SOURCE_CAMERA":            1,
		"SOURCE_MICROPHONE":        2,
		"SOURCE_SCREENSHARE":       3,
		"SOURCE_SCREENSHARE_AUDIO": 4,
	}
)

func (x TrackSource) Enum() *TrackSource {
	p := new(TrackSource)
	*p = x
	return p
}

func (x TrackSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackSource) Descriptor() protoreflect.EnumDescriptor {
	return file_track_proto_enumTypes[1].Descriptor()
}

func (TrackSource) Type() protoreflect.EnumType {
	return &file_track_proto_enumTypes[1]
}

func (x TrackSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TrackSource) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TrackSource(num)
	return nil
}

// Deprecated: Use TrackSource.Descriptor instead.
func (TrackSource) EnumDescriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{1}
}

type StreamState int32

const (
	StreamState_STATE_UNKNOWN StreamState = 0
	StreamState_STATE_ACTIVE  StreamState = 1
	StreamState_STATE_PAUSED  StreamState = 2
)

// Enum value maps for StreamState.
var (
	StreamState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "STATE_ACTIVE",
		2: "STATE_PAUSED",
	}
	StreamState_value = map[string]int32{
		"STATE_UNKNOWN": 0,
		"STATE_ACTIVE":  1,
		"STATE_PAUSED":  2,
	}
)

func (x StreamState) Enum() *StreamState {
	p := new(StreamState)
	*p = x
	return p
}

func (x StreamState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamState) Descriptor() protoreflect.EnumDescriptor {
	return file_track_proto_enumTypes[2].Descriptor()
}

func (StreamState) Type() protoreflect.EnumType {
	return &file_track_proto_enumTypes[2]
}

func (x StreamState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StreamState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StreamState(num)
	return nil
}

// Deprecated: Use StreamState.Descriptor instead.
func (StreamState) EnumDescriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{2}
}

type AudioTrackFeature int32

const (
	AudioTrackFeature_TF_STEREO                      AudioTrackFeature = 0
	AudioTrackFeature_TF_NO_DTX                      AudioTrackFeature = 1
	AudioTrackFeature_TF_AUTO_GAIN_CONTROL           AudioTrackFeature = 2
	AudioTrackFeature_TF_ECHO_CANCELLATION           AudioTrackFeature = 3
	AudioTrackFeature_TF_NOISE_SUPPRESSION           AudioTrackFeature = 4
	AudioTrackFeature_TF_ENHANCED_NOISE_CANCELLATION AudioTrackFeature = 5
	AudioTrackFeature_TF_PRECONNECT_BUFFER           AudioTrackFeature = 6 // client will buffer audio once available and send it to the server via bytes stream once connected
)

// Enum value maps for AudioTrackFeature.
var (
	AudioTrackFeature_name = map[int32]string{
		0: "TF_STEREO",
		1: "TF_NO_DTX",
		2: "TF_AUTO_GAIN_CONTROL",
		3: "TF_ECHO_CANCELLATION",
		4: "TF_NOISE_SUPPRESSION",
		5: "TF_ENHANCED_NOISE_CANCELLATION",
		6: "TF_PRECONNECT_BUFFER",
	}
	AudioTrackFeature_value = map[string]int32{
		"TF_STEREO":                      0,
		"TF_NO_DTX":                      1,
		"TF_AUTO_GAIN_CONTROL":           2,
		"TF_ECHO_CANCELLATION":           3,
		"TF_NOISE_SUPPRESSION":           4,
		"TF_ENHANCED_NOISE_CANCELLATION": 5,
		"TF_PRECONNECT_BUFFER":           6,
	}
)

func (x AudioTrackFeature) Enum() *AudioTrackFeature {
	p := new(AudioTrackFeature)
	*p = x
	return p
}

func (x AudioTrackFeature) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioTrackFeature) Descriptor() protoreflect.EnumDescriptor {
	return file_track_proto_enumTypes[3].Descriptor()
}

func (AudioTrackFeature) Type() protoreflect.EnumType {
	return &file_track_proto_enumTypes[3]
}

func (x AudioTrackFeature) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AudioTrackFeature) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AudioTrackFeature(num)
	return nil
}

// Deprecated: Use AudioTrackFeature.Descriptor instead.
func (AudioTrackFeature) EnumDescriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{3}
}

// Create a new VideoTrack from a VideoSource
type CreateVideoTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	SourceHandle  *uint64                `protobuf:"varint,2,req,name=source_handle,json=sourceHandle" json:"source_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoTrackRequest) Reset() {
	*x = CreateVideoTrackRequest{}
	mi := &file_track_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoTrackRequest) ProtoMessage() {}

func (x *CreateVideoTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoTrackRequest.ProtoReflect.Descriptor instead.
func (*CreateVideoTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVideoTrackRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateVideoTrackRequest) GetSourceHandle() uint64 {
	if x != nil && x.SourceHandle != nil {
		return *x.SourceHandle
	}
	return 0
}

type CreateVideoTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *OwnedTrack            `protobuf:"bytes,1,req,name=track" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoTrackResponse) Reset() {
	*x = CreateVideoTrackResponse{}
	mi := &file_track_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoTrackResponse) ProtoMessage() {}

func (x *CreateVideoTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoTrackResponse.ProtoReflect.Descriptor instead.
func (*CreateVideoTrackResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVideoTrackResponse) GetTrack() *OwnedTrack {
	if x != nil {
		return x.Track
	}
	return nil
}

// Create a new AudioTrack from a AudioSource
type CreateAudioTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	SourceHandle  *uint64                `protobuf:"varint,2,req,name=source_handle,json=sourceHandle" json:"source_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAudioTrackRequest) Reset() {
	*x = CreateAudioTrackRequest{}
	mi := &file_track_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAudioTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAudioTrackRequest) ProtoMessage() {}

func (x *CreateAudioTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAudioTrackRequest.ProtoReflect.Descriptor instead.
func (*CreateAudioTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAudioTrackRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateAudioTrackRequest) GetSourceHandle() uint64 {
	if x != nil && x.SourceHandle != nil {
		return *x.SourceHandle
	}
	return 0
}

type CreateAudioTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *OwnedTrack            `protobuf:"bytes,1,req,name=track" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAudioTrackResponse) Reset() {
	*x = CreateAudioTrackResponse{}
	mi := &file_track_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAudioTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAudioTrackResponse) ProtoMessage() {}

func (x *CreateAudioTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAudioTrackResponse.ProtoReflect.Descriptor instead.
func (*CreateAudioTrackResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAudioTrackResponse) GetTrack() *OwnedTrack {
	if x != nil {
		return x.Track
	}
	return nil
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackHandle   *uint64                `protobuf:"varint,1,req,name=track_handle,json=trackHandle" json:"track_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_track_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatsRequest) GetTrackHandle() uint64 {
	if x != nil && x.TrackHandle != nil {
		return *x.TrackHandle
	}
	return 0
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsyncId       *uint64                `protobuf:"varint,1,req,name=async_id,json=asyncId" json:"async_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_track_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatsResponse) GetAsyncId() uint64 {
	if x != nil && x.AsyncId != nil {
		return *x.AsyncId
	}
	return 0
}

type GetStatsCallback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsyncId       *uint64                `protobuf:"varint,1,req,name=async_id,json=asyncId" json:"async_id,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Stats         []*RtcStats            `protobuf:"bytes,3,rep,name=stats" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsCallback) Reset() {
	*x = GetStatsCallback{}
	mi := &file_track_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsCallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsCallback) ProtoMessage() {}

func (x *GetStatsCallback) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsCallback.ProtoReflect.Descriptor instead.
func (*GetStatsCallback) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatsCallback) GetAsyncId() uint64 {
	if x != nil && x.AsyncId != nil {
		return *x.AsyncId
	}
	return 0
}

func (x *GetStatsCallback) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetStatsCallback) GetStats() []*RtcStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type TrackEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEvent) Reset() {
	*x = TrackEvent{}
	mi := &file_track_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEvent) ProtoMessage() {}

func (x *TrackEvent) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEvent.ProtoReflect.Descriptor instead.
func (*TrackEvent) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{7}
}

type TrackPublicationInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sid            *string                `protobuf:"bytes,1,req,name=sid" json:"sid,omitempty"`
	Name           *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Kind           *TrackKind             `protobuf:"varint,3,req,name=kind,enum=livekit.proto.TrackKind" json:"kind,omitempty"`
	Source         *TrackSource           `protobuf:"varint,4,req,name=source,enum=livekit.proto.TrackSource" json:"source,omitempty"`
	Simulcasted    *bool                  `protobuf:"varint,5,req,name=simulcasted" json:"simulcasted,omitempty"`
	Width          *uint32                `protobuf:"varint,6,req,name=width" json:"width,omitempty"`
	Height         *uint32                `protobuf:"varint,7,req,name=height" json:"height,omitempty"`
	MimeType       *string                `protobuf:"bytes,8,req,name=mime_type,json=mimeType" json:"mime_type,omitempty"`
	Muted          *bool                  `protobuf:"varint,9,req,name=muted" json:"muted,omitempty"`
	Remote         *bool                  `protobuf:"varint,10,req,name=remote" json:"remote,omitempty"`
	EncryptionType *EncryptionType        `protobuf:"varint,11,req,name=encryption_type,json=encryptionType,enum=livekit.proto.EncryptionType" json:"encryption_type,omitempty"`
	AudioFeatures  []AudioTrackFeature    `protobuf:"varint,12,rep,name=audio_features,json=audioFeatures,enum=livekit.proto.AudioTrackFeature" json:"audio_features,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrackPublicationInfo) Reset() {
	*x = TrackPublicationInfo{}
	mi := &file_track_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPublicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPublicationInfo) ProtoMessage() {}

func (x *TrackPublicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPublicationInfo.ProtoReflect.Descriptor instead.
func (*TrackPublicationInfo) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{8}
}

func (x *TrackPublicationInfo) GetSid() string {
	if x != nil && x.Sid != nil {
		return *x.Sid
	}
	return ""
}

func (x *TrackPublicationInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TrackPublicationInfo) GetKind() TrackKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return TrackKind_KIND_UNKNOWN
}

func (x *TrackPublicationInfo) GetSource() TrackSource {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return TrackSource_SOURCE_UNKNOWN
}

func (x *TrackPublicationInfo) GetSimulcasted() bool {
	if x != nil && x.Simulcasted != nil {
		return *x.Simulcasted
	}
	return false
}

func (x *TrackPublicationInfo) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *TrackPublicationInfo) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *TrackPublicationInfo) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *TrackPublicationInfo) GetMuted() bool {
	if x != nil && x.Muted != nil {
		return *x.Muted
	}
	return false
}

func (x *TrackPublicationInfo) GetRemote() bool {
	if x != nil && x.Remote != nil {
		return *x.Remote
	}
	return false
}

func (x *TrackPublicationInfo) GetEncryptionType() EncryptionType {
	if x != nil && x.EncryptionType != nil {
		return *x.EncryptionType
	}
	return EncryptionType_NONE
}

func (x *TrackPublicationInfo) GetAudioFeatures() []AudioTrackFeature {
	if x != nil {
		return x.AudioFeatures
	}
	return nil
}

type OwnedTrackPublication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *FfiOwnedHandle        `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Info          *TrackPublicationInfo  `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedTrackPublication) Reset() {
	*x = OwnedTrackPublication{}
	mi := &file_track_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedTrackPublication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedTrackPublication) ProtoMessage() {}

func (x *OwnedTrackPublication) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedTrackPublication.ProtoReflect.Descriptor instead.
func (*OwnedTrackPublication) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{9}
}

func (x *OwnedTrackPublication) GetHandle() *FfiOwnedHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *OwnedTrackPublication) GetInfo() *TrackPublicationInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type TrackInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           *string                `protobuf:"bytes,1,req,name=sid" json:"sid,omitempty"`
	Name          *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Kind          *TrackKind             `protobuf:"varint,3,req,name=kind,enum=livekit.proto.TrackKind" json:"kind,omitempty"`
	StreamState   *StreamState           `protobuf:"varint,4,req,name=stream_state,json=streamState,enum=livekit.proto.StreamState" json:"stream_state,omitempty"`
	Muted         *bool                  `protobuf:"varint,5,req,name=muted" json:"muted,omitempty"`
	Remote        *bool                  `protobuf:"varint,6,req,name=remote" json:"remote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackInfo) Reset() {
	*x = TrackInfo{}
	mi := &file_track_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackInfo) ProtoMessage() {}

func (x *TrackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackInfo.ProtoReflect.Descriptor instead.
func (*TrackInfo) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{10}
}

func (x *TrackInfo) GetSid() string {
	if x != nil && x.Sid != nil {
		return *x.Sid
	}
	return ""
}

func (x *TrackInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TrackInfo) GetKind() TrackKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return TrackKind_KIND_UNKNOWN
}

func (x *TrackInfo) GetStreamState() StreamState {
	if x != nil && x.StreamState != nil {
		return *x.StreamState
	}
	return StreamState_STATE_UNKNOWN
}

func (x *TrackInfo) GetMuted() bool {
	if x != nil && x.Muted != nil {
		return *x.Muted
	}
	return false
}

func (x *TrackInfo) GetRemote() bool {
	if x != nil && x.Remote != nil {
		return *x.Remote
	}
	return false
}

type OwnedTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *FfiOwnedHandle        `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Info          *TrackInfo             `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedTrack) Reset() {
	*x = OwnedTrack{}
	mi := &file_track_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedTrack) ProtoMessage() {}

func (x *OwnedTrack) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedTrack.ProtoReflect.Descriptor instead.
func (*OwnedTrack) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{11}
}

func (x *OwnedTrack) GetHandle() *FfiOwnedHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *OwnedTrack) GetInfo() *TrackInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// Mute/UnMute a track
type LocalTrackMuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackHandle   *uint64                `protobuf:"varint,1,req,name=track_handle,json=trackHandle" json:"track_handle,omitempty"`
	Mute          *bool                  `protobuf:"varint,2,req,name=mute" json:"mute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalTrackMuteRequest) Reset() {
	*x = LocalTrackMuteRequest{}
	mi := &file_track_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalTrackMuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalTrackMuteRequest) ProtoMessage() {}

func (x *LocalTrackMuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalTrackMuteRequest.ProtoReflect.Descriptor instead.
func (*LocalTrackMuteRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{12}
}

func (x *LocalTrackMuteRequest) GetTrackHandle() uint64 {
	if x != nil && x.TrackHandle != nil {
		return *x.TrackHandle
	}
	return 0
}

func (x *LocalTrackMuteRequest) GetMute() bool {
	if x != nil && x.Mute != nil {
		return *x.Mute
	}
	return false
}

type LocalTrackMuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Muted         *bool                  `protobuf:"varint,1,req,name=muted" json:"muted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalTrackMuteResponse) Reset() {
	*x = LocalTrackMuteResponse{}
	mi := &file_track_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalTrackMuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalTrackMuteResponse) ProtoMessage() {}

func (x *LocalTrackMuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalTrackMuteResponse.ProtoReflect.Descriptor instead.
func (*LocalTrackMuteResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{13}
}

func (x *LocalTrackMuteResponse) GetMuted() bool {
	if x != nil && x.Muted != nil {
		return *x.Muted
	}
	return false
}

// Enable/Disable a remote track
type EnableRemoteTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackHandle   *uint64                `protobuf:"varint,1,req,name=track_handle,json=trackHandle" json:"track_handle,omitempty"`
	Enabled       *bool                  `protobuf:"varint,2,req,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRemoteTrackRequest) Reset() {
	*x = EnableRemoteTrackRequest{}
	mi := &file_track_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRemoteTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRemoteTrackRequest) ProtoMessage() {}

func (x *EnableRemoteTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRemoteTrackRequest.ProtoReflect.Descriptor instead.
func (*EnableRemoteTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{14}
}

func (x *EnableRemoteTrackRequest) GetTrackHandle() uint64 {
	if x != nil && x.TrackHandle != nil {
		return *x.TrackHandle
	}
	return 0
}

func (x *EnableRemoteTrackRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type EnableRemoteTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,req,name=enabled" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRemoteTrackResponse) Reset() {
	*x = EnableRemoteTrackResponse{}
	mi := &file_track_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRemoteTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRemoteTrackResponse) ProtoMessage() {}

func (x *EnableRemoteTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRemoteTrackResponse.ProtoReflect.Descriptor instead.
func (*EnableRemoteTrackResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{15}
}

func (x *EnableRemoteTrackResponse) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type SetTrackSubscriptionPermissionsRequest struct {
	state                  protoimpl.MessageState        `protogen:"open.v1"`
	LocalParticipantHandle *uint64                       `protobuf:"varint,1,req,name=local_participant_handle,json=localParticipantHandle" json:"local_participant_handle,omitempty"`
	AllParticipantsAllowed *bool                         `protobuf:"varint,2,req,name=all_participants_allowed,json=allParticipantsAllowed" json:"all_participants_allowed,omitempty"`
	Permissions            []*ParticipantTrackPermission `protobuf:"bytes,3,rep,name=permissions" json:"permissions,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetTrackSubscriptionPermissionsRequest) Reset() {
	*x = SetTrackSubscriptionPermissionsRequest{}
	mi := &file_track_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTrackSubscriptionPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTrackSubscriptionPermissionsRequest) ProtoMessage() {}

func (x *SetTrackSubscriptionPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTrackSubscriptionPermissionsRequest.ProtoReflect.Descriptor instead.
func (*SetTrackSubscriptionPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{16}
}

func (x *SetTrackSubscriptionPermissionsRequest) GetLocalParticipantHandle() uint64 {
	if x != nil && x.LocalParticipantHandle != nil {
		return *x.LocalParticipantHandle
	}
	return 0
}

func (x *SetTrackSubscriptionPermissionsRequest) GetAllParticipantsAllowed() bool {
	if x != nil && x.AllParticipantsAllowed != nil {
		return *x.AllParticipantsAllowed
	}
	return false
}

func (x *SetTrackSubscriptionPermissionsRequest) GetPermissions() []*ParticipantTrackPermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ParticipantTrackPermission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The participant identity this permission applies to.
	ParticipantIdentity *string `protobuf:"bytes,1,req,name=participant_identity,json=participantIdentity" json:"participant_identity,omitempty"`
	// Grant permission to all all tracks. Takes precedence over allowedTrackSids.
	AllowAll *bool `protobuf:"varint,2,opt,name=allow_all,json=allowAll" json:"allow_all,omitempty"`
	// List of track sids to grant permission to.
	AllowedTrackSids []string `protobuf:"bytes,3,rep,name=allowed_track_sids,json=allowedTrackSids" json:"allowed_track_sids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ParticipantTrackPermission) Reset() {
	*x = ParticipantTrackPermission{}
	mi := &file_track_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantTrackPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantTrackPermission) ProtoMessage() {}

func (x *ParticipantTrackPermission) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantTrackPermission.ProtoReflect.Descriptor instead.
func (*ParticipantTrackPermission) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{17}
}

func (x *ParticipantTrackPermission) GetParticipantIdentity() string {
	if x != nil && x.ParticipantIdentity != nil {
		return *x.ParticipantIdentity
	}
	return ""
}

func (x *ParticipantTrackPermission) GetAllowAll() bool {
	if x != nil && x.AllowAll != nil {
		return *x.AllowAll
	}
	return false
}

func (x *ParticipantTrackPermission) GetAllowedTrackSids() []string {
	if x != nil {
		return x.AllowedTrackSids
	}
	return nil
}

type SetTrackSubscriptionPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTrackSubscriptionPermissionsResponse) Reset() {
	*x = SetTrackSubscriptionPermissionsResponse{}
	mi := &file_track_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTrackSubscriptionPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTrackSubscriptionPermissionsResponse) ProtoMessage() {}

func (x *SetTrackSubscriptionPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTrackSubscriptionPermissionsResponse.ProtoReflect.Descriptor instead.
func (*SetTrackSubscriptionPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{18}
}

var File_track_proto protoreflect.FileDescriptor

const file_track_proto_rawDesc = "" +
	"\n" +
	"\vtrack.proto\x12\rlivekit.proto\x1a\n" +
	"e2ee.proto\x1a\fhandle.proto\x1a\vstats.proto\"R\n" +
	"\x17CreateVideoTrackRequest\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12#\n" +
	"\rsource_handle\x18\x02 \x02(\x04R\fsourceHandle\"K\n" +
	"\x18CreateVideoTrackResponse\x12/\n" +
	"\x05track\x18\x01 \x02(\v2\x19.livekit.proto.OwnedTrackR\x05track\"R\n" +
	"\x17CreateAudioTrackRequest\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12#\n" +
	"\rsource_handle\x18\x02 \x02(\x04R\fsourceHandle\"K\n" +
	"\x18CreateAudioTrackResponse\x12/\n" +
	"\x05track\x18\x01 \x02(\v2\x19.livekit.proto.OwnedTrackR\x05track\"4\n" +
	"\x0fGetStatsRequest\x12!\n" +
	"\ftrack_handle\x18\x01 \x02(\x04R\vtrackHandle\"-\n" +
	"\x10GetStatsResponse\x12\x19\n" +
	"\basync_id\x18\x01 \x02(\x04R\aasyncId\"r\n" +
	"\x10GetStatsCallback\x12\x19\n" +
	"\basync_id\x18\x01 \x02(\x04R\aasyncId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12-\n" +
	"\x05stats\x18\x03 \x03(\v2\x17.livekit.proto.RtcStatsR\x05stats\"\f\n" +
	"\n" +
	"TrackEvent\"\xca\x03\n" +
	"\x14TrackPublicationInfo\x12\x10\n" +
	"\x03sid\x18\x01 \x02(\tR\x03sid\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12,\n" +
	"\x04kind\x18\x03 \x02(\x0e2\x18.livekit.proto.TrackKindR\x04kind\x122\n" +
	"\x06source\x18\x04 \x02(\x0e2\x1a.livekit.proto.TrackSourceR\x06source\x12 \n" +
	"\vsimulcasted\x18\x05 \x02(\bR\vsimulcasted\x12\x14\n" +
	"\x05width\x18\x06 \x02(\rR\x05width\x12\x16\n" +
	"\x06height\x18\a \x02(\rR\x06height\x12\x1b\n" +
	"\tmime_type\x18\b \x02(\tR\bmimeType\x12\x14\n" +
	"\x05muted\x18\t \x02(\bR\x05muted\x12\x16\n" +
	"\x06remote\x18\n" +
	" \x02(\bR\x06remote\x12F\n" +
	"\x0fencryption_type\x18\v \x02(\x0e2\x1d.livekit.proto.EncryptionTypeR\x0eencryptionType\x12G\n" +
	"\x0eaudio_features\x18\f \x03(\x0e2 .livekit.proto.AudioTrackFeatureR\raudioFeatures\"\x87\x01\n" +
	"\x15OwnedTrackPublication\x125\n" +
	"\x06handle\x18\x01 \x02(\v2\x1d.livekit.proto.FfiOwnedHandleR\x06handle\x127\n" +
	"\x04info\x18\x02 \x02(\v2#.livekit.proto.TrackPublicationInfoR\x04info\"\xcc\x01\n" +
	"\tTrackInfo\x12\x10\n" +
	"\x03sid\x18\x01 \x02(\tR\x03sid\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12,\n" +
	"\x04kind\x18\x03 \x02(\x0e2\x18.livekit.proto.TrackKindR\x04kind\x12=\n" +
	"\fstream_state\x18\x04 \x02(\x0e2\x1a.livekit.proto.StreamStateR\vstreamState\x12\x14\n" +
	"\x05muted\x18\x05 \x02(\bR\x05muted\x12\x16\n" +
	"\x06remote\x18\x06 \x02(\bR\x06remote\"q\n" +
	"\n" +
	"OwnedTrack\x125\n" +
	"\x06handle\x18\x01 \x02(\v2\x1d.livekit.proto.FfiOwnedHandleR\x06handle\x12,\n" +
	"\x04info\x18\x02 \x02(\v2\x18.livekit.proto.TrackInfoR\x04info\"N\n" +
	"\x15LocalTrackMuteRequest\x12!\n" +
	"\ftrack_handle\x18\x01 \x02(\x04R\vtrackHandle\x12\x12\n" +
	"\x04mute\x18\x02 \x02(\bR\x04mute\".\n" +
	"\x16LocalTrackMuteResponse\x12\x14\n" +
	"\x05muted\x18\x01 \x02(\bR\x05muted\"W\n" +
	"\x18EnableRemoteTrackRequest\x12!\n" +
	"\ftrack_handle\x18\x01 \x02(\x04R\vtrackHandle\x12\x18\n" +
	"\aenabled\x18\x02 \x02(\bR\aenabled\"5\n" +
	"\x19EnableRemoteTrackResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x02(\bR\aenabled\"\xe9\x01\n" +
	"&SetTrackSubscriptionPermissionsRequest\x128\n" +
	"\x18local_participant_handle\x18\x01 \x02(\x04R\x16localParticipantHandle\x128\n" +
	"\x18all_participants_allowed\x18\x02 \x02(\bR\x16allParticipantsAllowed\x12K\n" +
	"\vpermissions\x18\x03 \x03(\v2).livekit.proto.ParticipantTrackPermissionR\vpermissions\"\x9a\x01\n" +
	"\x1aParticipantTrackPermission\x121\n" +
	"\x14participant_identity\x18\x01 \x02(\tR\x13participantIdentity\x12\x1b\n" +
	"\tallow_all\x18\x02 \x01(\bR\ballowAll\x12,\n" +
	"\x12allowed_track_sids\x18\x03 \x03(\tR\x10allowedTrackSids\")\n" +
	"'SetTrackSubscriptionPermissionsResponse*=\n" +
	"\tTrackKind\x12\x10\n" +
	"\fKIND_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_AUDIO\x10\x01\x12\x0e\n" +
	"\n" +
	"KIND_VIDEO\x10\x02*\x81\x01\n" +
	"\vTrackSource\x12\x12\n" +
	"\x0eSOURCE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSOURCE_CAMERA\x10\x01\x12\x15\n" +
	"\x11SOURCE_MICROPHONE\x10\x02\x12\x16\n" +
	"\x12SOURCE_SCREENSHARE\x10\x03\x12\x1c\n" +
	"\x18SOURCE_SCREENSHARE_AUDIO\x10\x04*D\n" +
	"\vStreamState\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fSTATE_ACTIVE\x10\x01\x12\x10\n" +
	"\fSTATE_PAUSED\x10\x02*\xbd\x01\n" +
	"\x11AudioTrackFeature\x12\r\n" +
	"\tTF_STEREO\x10\x00\x12\r\n" +
	"\tTF_NO_DTX\x10\x01\x12\x18\n" +
	"\x14TF_AUTO_GAIN_CONTROL\x10\x02\x12\x18\n" +
	"\x14TF_ECHO_CANCELLATION\x10\x03\x12\x18\n" +
	"\x14TF_NOISE_SUPPRESSION\x10\x04\x12\"\n" +
	"\x1eTF_ENHANCED_NOISE_CANCELLATION\x10\x05\x12\x18\n" +
	"\x14TF_PRECONNECT_BUFFER\x10\x06B\x19Z\a./proto\xaa\x02\rLiveKit.Proto"

var (
	file_track_proto_rawDescOnce sync.Once
	file_track_proto_rawDescData []byte
)

func file_track_proto_rawDescGZIP() []byte {
	file_track_proto_rawDescOnce.Do(func() {
		file_track_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_track_proto_rawDesc), len(file_track_proto_rawDesc)))
	})
	return file_track_proto_rawDescData
}

var file_track_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_track_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_track_proto_goTypes = []any{
	(TrackKind)(0),                                  // 0: livekit.proto.TrackKind
	(TrackSource)(0),                                // 1: livekit.proto.TrackSource
	(StreamState)(0),                                // 2: livekit.proto.StreamState
	(AudioTrackFeature)(0),                          // 3: livekit.proto.AudioTrackFeature
	(*CreateVideoTrackRequest)(nil),                 // 4: livekit.proto.CreateVideoTrackRequest
	(*CreateVideoTrackResponse)(nil),                // 5: livekit.proto.CreateVideoTrackResponse
	(*CreateAudioTrackRequest)(nil),                 // 6: livekit.proto.CreateAudioTrackRequest
	(*CreateAudioTrackResponse)(nil),                // 7: livekit.proto.CreateAudioTrackResponse
	(*GetStatsRequest)(nil),                         // 8: livekit.proto.GetStatsRequest
	(*GetStatsResponse)(nil),                        // 9: livekit.proto.GetStatsResponse
	(*GetStatsCallback)(nil),                        // 10: livekit.proto.GetStatsCallback
	(*TrackEvent)(nil),                              // 11: livekit.proto.TrackEvent
	(*TrackPublicationInfo)(nil),                    // 12: livekit.proto.TrackPublicationInfo
	(*OwnedTrackPublication)(nil),                   // 13: livekit.proto.OwnedTrackPublication
	(*TrackInfo)(nil),                               // 14: livekit.proto.TrackInfo
	(*OwnedTrack)(nil),                              // 15: livekit.proto.OwnedTrack
	(*LocalTrackMuteRequest)(nil),                   // 16: livekit.proto.LocalTrackMuteRequest
	(*LocalTrackMuteResponse)(nil),                  // 17: livekit.proto.LocalTrackMuteResponse
	(*EnableRemoteTrackRequest)(nil),                // 18: livekit.proto.EnableRemoteTrackRequest
	(*EnableRemoteTrackResponse)(nil),               // 19: livekit.proto.EnableRemoteTrackResponse
	(*SetTrackSubscriptionPermissionsRequest)(nil),  // 20: livekit.proto.SetTrackSubscriptionPermissionsRequest
	(*ParticipantTrackPermission)(nil),              // 21: livekit.proto.ParticipantTrackPermission
	(*SetTrackSubscriptionPermissionsResponse)(nil), // 22: livekit.proto.SetTrackSubscriptionPermissionsResponse
	(*RtcStats)(nil),                                // 23: livekit.proto.RtcStats
	(EncryptionType)(0),                             // 24: livekit.proto.EncryptionType
	(*FfiOwnedHandle)(nil),                          // 25: livekit.proto.FfiOwnedHandle
}
var file_track_proto_depIdxs = []int32{
	15, // 0: livekit.proto.CreateVideoTrackResponse.track:type_name -> livekit.proto.OwnedTrack
	15, // 1: livekit.proto.CreateAudioTrackResponse.track:type_name -> livekit.proto.OwnedTrack
	23, // 2: livekit.proto.GetStatsCallback.stats:type_name -> livekit.proto.RtcStats
	0,  // 3: livekit.proto.TrackPublicationInfo.kind:type_name -> livekit.proto.TrackKind
	1,  // 4: livekit.proto.TrackPublicationInfo.source:type_name -> livekit.proto.TrackSource
	24, // 5: livekit.proto.TrackPublicationInfo.encryption_type:type_name -> livekit.proto.EncryptionType
	3,  // 6: livekit.proto.TrackPublicationInfo.audio_features:type_name -> livekit.proto.AudioTrackFeature
	25, // 7: livekit.proto.OwnedTrackPublication.handle:type_name -> livekit.proto.FfiOwnedHandle
	12, // 8: livekit.proto.OwnedTrackPublication.info:type_name -> livekit.proto.TrackPublicationInfo
	0,  // 9: livekit.proto.TrackInfo.kind:type_name -> livekit.proto.TrackKind
	2,  // 10: livekit.proto.TrackInfo.stream_state:type_name -> livekit.proto.StreamState
	25, // 11: livekit.proto.OwnedTrack.handle:type_name -> livekit.proto.FfiOwnedHandle
	14, // 12: livekit.proto.OwnedTrack.info:type_name -> livekit.proto.TrackInfo
	21, // 13: livekit.proto.SetTrackSubscriptionPermissionsRequest.permissions:type_name -> livekit.proto.ParticipantTrackPermission
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_track_proto_init() }
func file_track_proto_init() {
	if File_track_proto != nil {
		return
	}
	file_e2ee_proto_init()
	file_handle_proto_init()
	file_stats_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_track_proto_rawDesc), len(file_track_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_track_proto_goTypes,
		DependencyIndexes: file_track_proto_depIdxs,
		EnumInfos:         file_track_proto_enumTypes,
		MessageInfos:      file_track_proto_msgTypes,
	}.Build()
	File_track_proto = out.File
	file_track_proto_goTypes = nil
	file_track_proto_depIdxs = nil
}
