// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: track_publication.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enable/Disable a remote track publication
type EnableRemoteTrackPublicationRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TrackPublicationHandle *uint64                `protobuf:"varint,1,req,name=track_publication_handle,json=trackPublicationHandle" json:"track_publication_handle,omitempty"`
	Enabled                *bool                  `protobuf:"varint,2,req,name=enabled" json:"enabled,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EnableRemoteTrackPublicationRequest) Reset() {
	*x = EnableRemoteTrackPublicationRequest{}
	mi := &file_track_publication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRemoteTrackPublicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRemoteTrackPublicationRequest) ProtoMessage() {}

func (x *EnableRemoteTrackPublicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_publication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRemoteTrackPublicationRequest.ProtoReflect.Descriptor instead.
func (*EnableRemoteTrackPublicationRequest) Descriptor() ([]byte, []int) {
	return file_track_publication_proto_rawDescGZIP(), []int{0}
}

func (x *EnableRemoteTrackPublicationRequest) GetTrackPublicationHandle() uint64 {
	if x != nil && x.TrackPublicationHandle != nil {
		return *x.TrackPublicationHandle
	}
	return 0
}

func (x *EnableRemoteTrackPublicationRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type EnableRemoteTrackPublicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRemoteTrackPublicationResponse) Reset() {
	*x = EnableRemoteTrackPublicationResponse{}
	mi := &file_track_publication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRemoteTrackPublicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRemoteTrackPublicationResponse) ProtoMessage() {}

func (x *EnableRemoteTrackPublicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_publication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRemoteTrackPublicationResponse.ProtoReflect.Descriptor instead.
func (*EnableRemoteTrackPublicationResponse) Descriptor() ([]byte, []int) {
	return file_track_publication_proto_rawDescGZIP(), []int{1}
}

// update a remote track publication dimension
type UpdateRemoteTrackPublicationDimensionRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TrackPublicationHandle *uint64                `protobuf:"varint,1,req,name=track_publication_handle,json=trackPublicationHandle" json:"track_publication_handle,omitempty"`
	Width                  *uint32                `protobuf:"varint,2,req,name=width" json:"width,omitempty"`
	Height                 *uint32                `protobuf:"varint,3,req,name=height" json:"height,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateRemoteTrackPublicationDimensionRequest) Reset() {
	*x = UpdateRemoteTrackPublicationDimensionRequest{}
	mi := &file_track_publication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRemoteTrackPublicationDimensionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRemoteTrackPublicationDimensionRequest) ProtoMessage() {}

func (x *UpdateRemoteTrackPublicationDimensionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_publication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRemoteTrackPublicationDimensionRequest.ProtoReflect.Descriptor instead.
func (*UpdateRemoteTrackPublicationDimensionRequest) Descriptor() ([]byte, []int) {
	return file_track_publication_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRemoteTrackPublicationDimensionRequest) GetTrackPublicationHandle() uint64 {
	if x != nil && x.TrackPublicationHandle != nil {
		return *x.TrackPublicationHandle
	}
	return 0
}

func (x *UpdateRemoteTrackPublicationDimensionRequest) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *UpdateRemoteTrackPublicationDimensionRequest) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

type UpdateRemoteTrackPublicationDimensionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRemoteTrackPublicationDimensionResponse) Reset() {
	*x = UpdateRemoteTrackPublicationDimensionResponse{}
	mi := &file_track_publication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRemoteTrackPublicationDimensionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRemoteTrackPublicationDimensionResponse) ProtoMessage() {}

func (x *UpdateRemoteTrackPublicationDimensionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_publication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRemoteTrackPublicationDimensionResponse.ProtoReflect.Descriptor instead.
func (*UpdateRemoteTrackPublicationDimensionResponse) Descriptor() ([]byte, []int) {
	return file_track_publication_proto_rawDescGZIP(), []int{3}
}

var File_track_publication_proto protoreflect.FileDescriptor

const file_track_publication_proto_rawDesc = "" +
	"\n" +
	"\x17track_publication.proto\x12\rlivekit.proto\"y\n" +
	"#EnableRemoteTrackPublicationRequest\x128\n" +
	"\x18track_publication_handle\x18\x01 \x02(\x04R\x16trackPublicationHandle\x12\x18\n" +
	"\aenabled\x18\x02 \x02(\bR\aenabled\"&\n" +
	"$EnableRemoteTrackPublicationResponse\"\x96\x01\n" +
	",UpdateRemoteTrackPublicationDimensionRequest\x128\n" +
	"\x18track_publication_handle\x18\x01 \x02(\x04R\x16trackPublicationHandle\x12\x14\n" +
	"\x05width\x18\x02 \x02(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x02(\rR\x06height\"/\n" +
	"-UpdateRemoteTrackPublicationDimensionResponseB\x19Z\a./proto\xaa\x02\rLiveKit.Proto"

var (
	file_track_publication_proto_rawDescOnce sync.Once
	file_track_publication_proto_rawDescData []byte
)

func file_track_publication_proto_rawDescGZIP() []byte {
	file_track_publication_proto_rawDescOnce.Do(func() {
		file_track_publication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_track_publication_proto_rawDesc), len(file_track_publication_proto_rawDesc)))
	})
	return file_track_publication_proto_rawDescData
}

var file_track_publication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_track_publication_proto_goTypes = []any{
	(*EnableRemoteTrackPublicationRequest)(nil),           // 0: livekit.proto.EnableRemoteTrackPublicationRequest
	(*EnableRemoteTrackPublicationResponse)(nil),          // 1: livekit.proto.EnableRemoteTrackPublicationResponse
	(*UpdateRemoteTrackPublicationDimensionRequest)(nil),  // 2: livekit.proto.UpdateRemoteTrackPublicationDimensionRequest
	(*UpdateRemoteTrackPublicationDimensionResponse)(nil), // 3: livekit.proto.UpdateRemoteTrackPublicationDimensionResponse
}
var file_track_publication_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_track_publication_proto_init() }
func file_track_publication_proto_init() {
	if File_track_publication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_track_publication_proto_rawDesc), len(file_track_publication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_track_publication_proto_goTypes,
		DependencyIndexes: file_track_publication_proto_depIdxs,
		MessageInfos:      file_track_publication_proto_msgTypes,
	}.Build()
	File_track_publication_proto = out.File
	file_track_publication_proto_goTypes = nil
	file_track_publication_proto_depIdxs = nil
}
