// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: video_frame.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoCodec int32

const (
	VideoCodec_VP8  VideoCodec = 0
	VideoCodec_H264 VideoCodec = 1
	VideoCodec_AV1  VideoCodec = 2
	VideoCodec_VP9  VideoCodec = 3
)

// Enum value maps for VideoCodec.
var (
	VideoCodec_name = map[int32]string{
		0: "VP8",
		1: "H264",
		2: "AV1",
		3: "VP9",
	}
	VideoCodec_value = map[string]int32{
		"VP8":  0,
		"H264": 1,
		"AV1":  2,
		"VP9":  3,
	}
)

func (x VideoCodec) Enum() *VideoCodec {
	p := new(VideoCodec)
	*p = x
	return p
}

func (x VideoCodec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoCodec) Descriptor() protoreflect.EnumDescriptor {
	return file_video_frame_proto_enumTypes[0].Descriptor()
}

func (VideoCodec) Type() protoreflect.EnumType {
	return &file_video_frame_proto_enumTypes[0]
}

func (x VideoCodec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *VideoCodec) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = VideoCodec(num)
	return nil
}

// Deprecated: Use VideoCodec.Descriptor instead.
func (VideoCodec) EnumDescriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{0}
}

type VideoRotation int32

const (
	VideoRotation_VIDEO_ROTATION_0   VideoRotation = 0
	VideoRotation_VIDEO_ROTATION_90  VideoRotation = 1
	VideoRotation_VIDEO_ROTATION_180 VideoRotation = 2
	VideoRotation_VIDEO_ROTATION_270 VideoRotation = 3
)

// Enum value maps for VideoRotation.
var (
	VideoRotation_name = map[int32]string{
		0: "VIDEO_ROTATION_0",
		1: "VIDEO_ROTATION_90",
		2: "VIDEO_ROTATION_180",
		3: "VIDEO_ROTATION_270",
	}
	VideoRotation_value = map[string]int32{
		"VIDEO_ROTATION_0":   0,
		"VIDEO_ROTATION_90":  1,
		"VIDEO_ROTATION_180": 2,
		"VIDEO_ROTATION_270": 3,
	}
)

func (x VideoRotation) Enum() *VideoRotation {
	p := new(VideoRotation)
	*p = x
	return p
}

func (x VideoRotation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoRotation) Descriptor() protoreflect.EnumDescriptor {
	return file_video_frame_proto_enumTypes[1].Descriptor()
}

func (VideoRotation) Type() protoreflect.EnumType {
	return &file_video_frame_proto_enumTypes[1]
}

func (x VideoRotation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *VideoRotation) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = VideoRotation(num)
	return nil
}

// Deprecated: Use VideoRotation.Descriptor instead.
func (VideoRotation) EnumDescriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{1}
}

// Values of this enum must not be changed
// It is used to serialize a rtc.VideoFrame on Python
type VideoBufferType int32

const (
	VideoBufferType_RGBA  VideoBufferType = 0
	VideoBufferType_ABGR  VideoBufferType = 1
	VideoBufferType_ARGB  VideoBufferType = 2
	VideoBufferType_BGRA  VideoBufferType = 3
	VideoBufferType_RGB24 VideoBufferType = 4
	VideoBufferType_I420  VideoBufferType = 5
	VideoBufferType_I420A VideoBufferType = 6
	VideoBufferType_I422  VideoBufferType = 7
	VideoBufferType_I444  VideoBufferType = 8
	VideoBufferType_I010  VideoBufferType = 9
	VideoBufferType_NV12  VideoBufferType = 10
)

// Enum value maps for VideoBufferType.
var (
	VideoBufferType_name = map[int32]string{
		0:  "RGBA",
		1:  "ABGR",
		2:  "ARGB",
		3:  "BGRA",
		4:  "RGB24",
		5:  "I420",
		6:  "I420A",
		7:  "I422",
		8:  "I444",
		9:  "I010",
		10: "NV12",
	}
	VideoBufferType_value = map[string]int32{
		"RGBA":  0,
		"ABGR":  1,
		"ARGB":  2,
		"BGRA":  3,
		"RGB24": 4,
		"I420":  5,
		"I420A": 6,
		"I422":  7,
		"I444":  8,
		"I010":  9,
		"NV12":  10,
	}
)

func (x VideoBufferType) Enum() *VideoBufferType {
	p := new(VideoBufferType)
	*p = x
	return p
}

func (x VideoBufferType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoBufferType) Descriptor() protoreflect.EnumDescriptor {
	return file_video_frame_proto_enumTypes[2].Descriptor()
}

func (VideoBufferType) Type() protoreflect.EnumType {
	return &file_video_frame_proto_enumTypes[2]
}

func (x VideoBufferType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *VideoBufferType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = VideoBufferType(num)
	return nil
}

// Deprecated: Use VideoBufferType.Descriptor instead.
func (VideoBufferType) EnumDescriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{2}
}

type VideoStreamType int32

const (
	VideoStreamType_VIDEO_STREAM_NATIVE VideoStreamType = 0
	VideoStreamType_VIDEO_STREAM_WEBGL  VideoStreamType = 1
	VideoStreamType_VIDEO_STREAM_HTML   VideoStreamType = 2
)

// Enum value maps for VideoStreamType.
var (
	VideoStreamType_name = map[int32]string{
		0: "VIDEO_STREAM_NATIVE",
		1: "VIDEO_STREAM_WEBGL",
		2: "VIDEO_STREAM_HTML",
	}
	VideoStreamType_value = map[string]int32{
		"VIDEO_STREAM_NATIVE": 0,
		"VIDEO_STREAM_WEBGL":  1,
		"VIDEO_STREAM_HTML":   2,
	}
)

func (x VideoStreamType) Enum() *VideoStreamType {
	p := new(VideoStreamType)
	*p = x
	return p
}

func (x VideoStreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoStreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_video_frame_proto_enumTypes[3].Descriptor()
}

func (VideoStreamType) Type() protoreflect.EnumType {
	return &file_video_frame_proto_enumTypes[3]
}

func (x VideoStreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *VideoStreamType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = VideoStreamType(num)
	return nil
}

// Deprecated: Use VideoStreamType.Descriptor instead.
func (VideoStreamType) EnumDescriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{3}
}

type VideoSourceType int32

const (
	VideoSourceType_VIDEO_SOURCE_NATIVE VideoSourceType = 0
)

// Enum value maps for VideoSourceType.
var (
	VideoSourceType_name = map[int32]string{
		0: "VIDEO_SOURCE_NATIVE",
	}
	VideoSourceType_value = map[string]int32{
		"VIDEO_SOURCE_NATIVE": 0,
	}
)

func (x VideoSourceType) Enum() *VideoSourceType {
	p := new(VideoSourceType)
	*p = x
	return p
}

func (x VideoSourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoSourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_video_frame_proto_enumTypes[4].Descriptor()
}

func (VideoSourceType) Type() protoreflect.EnumType {
	return &file_video_frame_proto_enumTypes[4]
}

func (x VideoSourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *VideoSourceType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = VideoSourceType(num)
	return nil
}

// Deprecated: Use VideoSourceType.Descriptor instead.
func (VideoSourceType) EnumDescriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{4}
}

// Create a new VideoStream
// VideoStream is used to receive video frames from a track
type NewVideoStreamRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TrackHandle *uint64                `protobuf:"varint,1,req,name=track_handle,json=trackHandle" json:"track_handle,omitempty"`
	Type        *VideoStreamType       `protobuf:"varint,2,req,name=type,enum=livekit.proto.VideoStreamType" json:"type,omitempty"`
	// Get the frame on a specific format
	Format          *VideoBufferType `protobuf:"varint,3,opt,name=format,enum=livekit.proto.VideoBufferType" json:"format,omitempty"`
	NormalizeStride *bool            `protobuf:"varint,4,opt,name=normalize_stride,json=normalizeStride" json:"normalize_stride,omitempty"` // if true, stride will be set to width/chroma_width
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NewVideoStreamRequest) Reset() {
	*x = NewVideoStreamRequest{}
	mi := &file_video_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewVideoStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewVideoStreamRequest) ProtoMessage() {}

func (x *NewVideoStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewVideoStreamRequest.ProtoReflect.Descriptor instead.
func (*NewVideoStreamRequest) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{0}
}

func (x *NewVideoStreamRequest) GetTrackHandle() uint64 {
	if x != nil && x.TrackHandle != nil {
		return *x.TrackHandle
	}
	return 0
}

func (x *NewVideoStreamRequest) GetType() VideoStreamType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return VideoStreamType_VIDEO_STREAM_NATIVE
}

func (x *NewVideoStreamRequest) GetFormat() VideoBufferType {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return VideoBufferType_RGBA
}

func (x *NewVideoStreamRequest) GetNormalizeStride() bool {
	if x != nil && x.NormalizeStride != nil {
		return *x.NormalizeStride
	}
	return false
}

type NewVideoStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *OwnedVideoStream      `protobuf:"bytes,1,req,name=stream" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewVideoStreamResponse) Reset() {
	*x = NewVideoStreamResponse{}
	mi := &file_video_frame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewVideoStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewVideoStreamResponse) ProtoMessage() {}

func (x *NewVideoStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewVideoStreamResponse.ProtoReflect.Descriptor instead.
func (*NewVideoStreamResponse) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{1}
}

func (x *NewVideoStreamResponse) GetStream() *OwnedVideoStream {
	if x != nil {
		return x.Stream
	}
	return nil
}

// Request a video stream from a participant
type VideoStreamFromParticipantRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ParticipantHandle *uint64                `protobuf:"varint,1,req,name=participant_handle,json=participantHandle" json:"participant_handle,omitempty"`
	Type              *VideoStreamType       `protobuf:"varint,2,req,name=type,enum=livekit.proto.VideoStreamType" json:"type,omitempty"`
	TrackSource       *TrackSource           `protobuf:"varint,3,req,name=track_source,json=trackSource,enum=livekit.proto.TrackSource" json:"track_source,omitempty"`
	Format            *VideoBufferType       `protobuf:"varint,4,opt,name=format,enum=livekit.proto.VideoBufferType" json:"format,omitempty"`
	NormalizeStride   *bool                  `protobuf:"varint,5,opt,name=normalize_stride,json=normalizeStride" json:"normalize_stride,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VideoStreamFromParticipantRequest) Reset() {
	*x = VideoStreamFromParticipantRequest{}
	mi := &file_video_frame_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStreamFromParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStreamFromParticipantRequest) ProtoMessage() {}

func (x *VideoStreamFromParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStreamFromParticipantRequest.ProtoReflect.Descriptor instead.
func (*VideoStreamFromParticipantRequest) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{2}
}

func (x *VideoStreamFromParticipantRequest) GetParticipantHandle() uint64 {
	if x != nil && x.ParticipantHandle != nil {
		return *x.ParticipantHandle
	}
	return 0
}

func (x *VideoStreamFromParticipantRequest) GetType() VideoStreamType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return VideoStreamType_VIDEO_STREAM_NATIVE
}

func (x *VideoStreamFromParticipantRequest) GetTrackSource() TrackSource {
	if x != nil && x.TrackSource != nil {
		return *x.TrackSource
	}
	return TrackSource_SOURCE_UNKNOWN
}

func (x *VideoStreamFromParticipantRequest) GetFormat() VideoBufferType {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return VideoBufferType_RGBA
}

func (x *VideoStreamFromParticipantRequest) GetNormalizeStride() bool {
	if x != nil && x.NormalizeStride != nil {
		return *x.NormalizeStride
	}
	return false
}

type VideoStreamFromParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *OwnedVideoStream      `protobuf:"bytes,1,req,name=stream" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoStreamFromParticipantResponse) Reset() {
	*x = VideoStreamFromParticipantResponse{}
	mi := &file_video_frame_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStreamFromParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStreamFromParticipantResponse) ProtoMessage() {}

func (x *VideoStreamFromParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStreamFromParticipantResponse.ProtoReflect.Descriptor instead.
func (*VideoStreamFromParticipantResponse) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{3}
}

func (x *VideoStreamFromParticipantResponse) GetStream() *OwnedVideoStream {
	if x != nil {
		return x.Stream
	}
	return nil
}

// Create a new VideoSource
// VideoSource is used to send video frame to a track
type NewVideoSourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  *VideoSourceType       `protobuf:"varint,1,req,name=type,enum=livekit.proto.VideoSourceType" json:"type,omitempty"`
	// Used to determine which encodings to use + simulcast layers
	// Most of the time it corresponds to the source resolution
	Resolution    *VideoSourceResolution `protobuf:"bytes,2,req,name=resolution" json:"resolution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewVideoSourceRequest) Reset() {
	*x = NewVideoSourceRequest{}
	mi := &file_video_frame_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewVideoSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewVideoSourceRequest) ProtoMessage() {}

func (x *NewVideoSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewVideoSourceRequest.ProtoReflect.Descriptor instead.
func (*NewVideoSourceRequest) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{4}
}

func (x *NewVideoSourceRequest) GetType() VideoSourceType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return VideoSourceType_VIDEO_SOURCE_NATIVE
}

func (x *NewVideoSourceRequest) GetResolution() *VideoSourceResolution {
	if x != nil {
		return x.Resolution
	}
	return nil
}

type NewVideoSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *OwnedVideoSource      `protobuf:"bytes,1,req,name=source" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewVideoSourceResponse) Reset() {
	*x = NewVideoSourceResponse{}
	mi := &file_video_frame_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewVideoSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewVideoSourceResponse) ProtoMessage() {}

func (x *NewVideoSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewVideoSourceResponse.ProtoReflect.Descriptor instead.
func (*NewVideoSourceResponse) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{5}
}

func (x *NewVideoSourceResponse) GetSource() *OwnedVideoSource {
	if x != nil {
		return x.Source
	}
	return nil
}

// Push a frame to a VideoSource
type CaptureVideoFrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceHandle  *uint64                `protobuf:"varint,1,req,name=source_handle,json=sourceHandle" json:"source_handle,omitempty"`
	Buffer        *VideoBufferInfo       `protobuf:"bytes,2,req,name=buffer" json:"buffer,omitempty"`
	TimestampUs   *int64                 `protobuf:"varint,3,req,name=timestamp_us,json=timestampUs" json:"timestamp_us,omitempty"` // In microseconds
	Rotation      *VideoRotation         `protobuf:"varint,4,req,name=rotation,enum=livekit.proto.VideoRotation" json:"rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureVideoFrameRequest) Reset() {
	*x = CaptureVideoFrameRequest{}
	mi := &file_video_frame_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureVideoFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureVideoFrameRequest) ProtoMessage() {}

func (x *CaptureVideoFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureVideoFrameRequest.ProtoReflect.Descriptor instead.
func (*CaptureVideoFrameRequest) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{6}
}

func (x *CaptureVideoFrameRequest) GetSourceHandle() uint64 {
	if x != nil && x.SourceHandle != nil {
		return *x.SourceHandle
	}
	return 0
}

func (x *CaptureVideoFrameRequest) GetBuffer() *VideoBufferInfo {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *CaptureVideoFrameRequest) GetTimestampUs() int64 {
	if x != nil && x.TimestampUs != nil {
		return *x.TimestampUs
	}
	return 0
}

func (x *CaptureVideoFrameRequest) GetRotation() VideoRotation {
	if x != nil && x.Rotation != nil {
		return *x.Rotation
	}
	return VideoRotation_VIDEO_ROTATION_0
}

type CaptureVideoFrameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureVideoFrameResponse) Reset() {
	*x = CaptureVideoFrameResponse{}
	mi := &file_video_frame_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureVideoFrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureVideoFrameResponse) ProtoMessage() {}

func (x *CaptureVideoFrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureVideoFrameResponse.ProtoReflect.Descriptor instead.
func (*CaptureVideoFrameResponse) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{7}
}

type VideoConvertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlipY         *bool                  `protobuf:"varint,1,opt,name=flip_y,json=flipY" json:"flip_y,omitempty"`
	Buffer        *VideoBufferInfo       `protobuf:"bytes,2,req,name=buffer" json:"buffer,omitempty"`
	DstType       *VideoBufferType       `protobuf:"varint,3,req,name=dst_type,json=dstType,enum=livekit.proto.VideoBufferType" json:"dst_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoConvertRequest) Reset() {
	*x = VideoConvertRequest{}
	mi := &file_video_frame_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoConvertRequest) ProtoMessage() {}

func (x *VideoConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoConvertRequest.ProtoReflect.Descriptor instead.
func (*VideoConvertRequest) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{8}
}

func (x *VideoConvertRequest) GetFlipY() bool {
	if x != nil && x.FlipY != nil {
		return *x.FlipY
	}
	return false
}

func (x *VideoConvertRequest) GetBuffer() *VideoBufferInfo {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *VideoConvertRequest) GetDstType() VideoBufferType {
	if x != nil && x.DstType != nil {
		return *x.DstType
	}
	return VideoBufferType_RGBA
}

type VideoConvertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*VideoConvertResponse_Error
	//	*VideoConvertResponse_Buffer
	Message       isVideoConvertResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoConvertResponse) Reset() {
	*x = VideoConvertResponse{}
	mi := &file_video_frame_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoConvertResponse) ProtoMessage() {}

func (x *VideoConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoConvertResponse.ProtoReflect.Descriptor instead.
func (*VideoConvertResponse) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{9}
}

func (x *VideoConvertResponse) GetMessage() isVideoConvertResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *VideoConvertResponse) GetError() string {
	if x != nil {
		if x, ok := x.Message.(*VideoConvertResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *VideoConvertResponse) GetBuffer() *OwnedVideoBuffer {
	if x != nil {
		if x, ok := x.Message.(*VideoConvertResponse_Buffer); ok {
			return x.Buffer
		}
	}
	return nil
}

type isVideoConvertResponse_Message interface {
	isVideoConvertResponse_Message()
}

type VideoConvertResponse_Error struct {
	Error string `protobuf:"bytes,1,opt,name=error,oneof"`
}

type VideoConvertResponse_Buffer struct {
	Buffer *OwnedVideoBuffer `protobuf:"bytes,2,opt,name=buffer,oneof"`
}

func (*VideoConvertResponse_Error) isVideoConvertResponse_Message() {}

func (*VideoConvertResponse_Buffer) isVideoConvertResponse_Message() {}

type VideoResolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         *uint32                `protobuf:"varint,1,req,name=width" json:"width,omitempty"`
	Height        *uint32                `protobuf:"varint,2,req,name=height" json:"height,omitempty"`
	FrameRate     *float64               `protobuf:"fixed64,3,req,name=frame_rate,json=frameRate" json:"frame_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoResolution) Reset() {
	*x = VideoResolution{}
	mi := &file_video_frame_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoResolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoResolution) ProtoMessage() {}

func (x *VideoResolution) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoResolution.ProtoReflect.Descriptor instead.
func (*VideoResolution) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{10}
}

func (x *VideoResolution) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *VideoResolution) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *VideoResolution) GetFrameRate() float64 {
	if x != nil && x.FrameRate != nil {
		return *x.FrameRate
	}
	return 0
}

type VideoBufferInfo struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Type          *VideoBufferType                 `protobuf:"varint,1,req,name=type,enum=livekit.proto.VideoBufferType" json:"type,omitempty"`
	Width         *uint32                          `protobuf:"varint,2,req,name=width" json:"width,omitempty"`
	Height        *uint32                          `protobuf:"varint,3,req,name=height" json:"height,omitempty"`
	DataPtr       *uint64                          `protobuf:"varint,4,req,name=data_ptr,json=dataPtr" json:"data_ptr,omitempty"`
	Stride        *uint32                          `protobuf:"varint,6,opt,name=stride" json:"stride,omitempty"` // only for packed formats
	Components    []*VideoBufferInfo_ComponentInfo `protobuf:"bytes,7,rep,name=components" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoBufferInfo) Reset() {
	*x = VideoBufferInfo{}
	mi := &file_video_frame_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoBufferInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoBufferInfo) ProtoMessage() {}

func (x *VideoBufferInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoBufferInfo.ProtoReflect.Descriptor instead.
func (*VideoBufferInfo) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{11}
}

func (x *VideoBufferInfo) GetType() VideoBufferType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return VideoBufferType_RGBA
}

func (x *VideoBufferInfo) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *VideoBufferInfo) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *VideoBufferInfo) GetDataPtr() uint64 {
	if x != nil && x.DataPtr != nil {
		return *x.DataPtr
	}
	return 0
}

func (x *VideoBufferInfo) GetStride() uint32 {
	if x != nil && x.Stride != nil {
		return *x.Stride
	}
	return 0
}

func (x *VideoBufferInfo) GetComponents() []*VideoBufferInfo_ComponentInfo {
	if x != nil {
		return x.Components
	}
	return nil
}

type OwnedVideoBuffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *FfiOwnedHandle        `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Info          *VideoBufferInfo       `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedVideoBuffer) Reset() {
	*x = OwnedVideoBuffer{}
	mi := &file_video_frame_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedVideoBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedVideoBuffer) ProtoMessage() {}

func (x *OwnedVideoBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedVideoBuffer.ProtoReflect.Descriptor instead.
func (*OwnedVideoBuffer) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{12}
}

func (x *OwnedVideoBuffer) GetHandle() *FfiOwnedHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *OwnedVideoBuffer) GetInfo() *VideoBufferInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type VideoStreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *VideoStreamType       `protobuf:"varint,1,req,name=type,enum=livekit.proto.VideoStreamType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoStreamInfo) Reset() {
	*x = VideoStreamInfo{}
	mi := &file_video_frame_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStreamInfo) ProtoMessage() {}

func (x *VideoStreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStreamInfo.ProtoReflect.Descriptor instead.
func (*VideoStreamInfo) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{13}
}

func (x *VideoStreamInfo) GetType() VideoStreamType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return VideoStreamType_VIDEO_STREAM_NATIVE
}

type OwnedVideoStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *FfiOwnedHandle        `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Info          *VideoStreamInfo       `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedVideoStream) Reset() {
	*x = OwnedVideoStream{}
	mi := &file_video_frame_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedVideoStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedVideoStream) ProtoMessage() {}

func (x *OwnedVideoStream) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedVideoStream.ProtoReflect.Descriptor instead.
func (*OwnedVideoStream) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{14}
}

func (x *OwnedVideoStream) GetHandle() *FfiOwnedHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *OwnedVideoStream) GetInfo() *VideoStreamInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type VideoStreamEvent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	StreamHandle *uint64                `protobuf:"varint,1,req,name=stream_handle,json=streamHandle" json:"stream_handle,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*VideoStreamEvent_FrameReceived
	//	*VideoStreamEvent_Eos
	Message       isVideoStreamEvent_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoStreamEvent) Reset() {
	*x = VideoStreamEvent{}
	mi := &file_video_frame_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStreamEvent) ProtoMessage() {}

func (x *VideoStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStreamEvent.ProtoReflect.Descriptor instead.
func (*VideoStreamEvent) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{15}
}

func (x *VideoStreamEvent) GetStreamHandle() uint64 {
	if x != nil && x.StreamHandle != nil {
		return *x.StreamHandle
	}
	return 0
}

func (x *VideoStreamEvent) GetMessage() isVideoStreamEvent_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *VideoStreamEvent) GetFrameReceived() *VideoFrameReceived {
	if x != nil {
		if x, ok := x.Message.(*VideoStreamEvent_FrameReceived); ok {
			return x.FrameReceived
		}
	}
	return nil
}

func (x *VideoStreamEvent) GetEos() *VideoStreamEOS {
	if x != nil {
		if x, ok := x.Message.(*VideoStreamEvent_Eos); ok {
			return x.Eos
		}
	}
	return nil
}

type isVideoStreamEvent_Message interface {
	isVideoStreamEvent_Message()
}

type VideoStreamEvent_FrameReceived struct {
	FrameReceived *VideoFrameReceived `protobuf:"bytes,2,opt,name=frame_received,json=frameReceived,oneof"`
}

type VideoStreamEvent_Eos struct {
	Eos *VideoStreamEOS `protobuf:"bytes,3,opt,name=eos,oneof"`
}

func (*VideoStreamEvent_FrameReceived) isVideoStreamEvent_Message() {}

func (*VideoStreamEvent_Eos) isVideoStreamEvent_Message() {}

type VideoFrameReceived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffer        *OwnedVideoBuffer      `protobuf:"bytes,1,req,name=buffer" json:"buffer,omitempty"`
	TimestampUs   *int64                 `protobuf:"varint,2,req,name=timestamp_us,json=timestampUs" json:"timestamp_us,omitempty"` // In microseconds
	Rotation      *VideoRotation         `protobuf:"varint,3,req,name=rotation,enum=livekit.proto.VideoRotation" json:"rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFrameReceived) Reset() {
	*x = VideoFrameReceived{}
	mi := &file_video_frame_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFrameReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFrameReceived) ProtoMessage() {}

func (x *VideoFrameReceived) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFrameReceived.ProtoReflect.Descriptor instead.
func (*VideoFrameReceived) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{16}
}

func (x *VideoFrameReceived) GetBuffer() *OwnedVideoBuffer {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *VideoFrameReceived) GetTimestampUs() int64 {
	if x != nil && x.TimestampUs != nil {
		return *x.TimestampUs
	}
	return 0
}

func (x *VideoFrameReceived) GetRotation() VideoRotation {
	if x != nil && x.Rotation != nil {
		return *x.Rotation
	}
	return VideoRotation_VIDEO_ROTATION_0
}

type VideoStreamEOS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoStreamEOS) Reset() {
	*x = VideoStreamEOS{}
	mi := &file_video_frame_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStreamEOS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStreamEOS) ProtoMessage() {}

func (x *VideoStreamEOS) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStreamEOS.ProtoReflect.Descriptor instead.
func (*VideoStreamEOS) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{17}
}

type VideoSourceResolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         *uint32                `protobuf:"varint,1,req,name=width" json:"width,omitempty"`
	Height        *uint32                `protobuf:"varint,2,req,name=height" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSourceResolution) Reset() {
	*x = VideoSourceResolution{}
	mi := &file_video_frame_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSourceResolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSourceResolution) ProtoMessage() {}

func (x *VideoSourceResolution) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSourceResolution.ProtoReflect.Descriptor instead.
func (*VideoSourceResolution) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{18}
}

func (x *VideoSourceResolution) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *VideoSourceResolution) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

type VideoSourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *VideoSourceType       `protobuf:"varint,1,req,name=type,enum=livekit.proto.VideoSourceType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSourceInfo) Reset() {
	*x = VideoSourceInfo{}
	mi := &file_video_frame_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSourceInfo) ProtoMessage() {}

func (x *VideoSourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSourceInfo.ProtoReflect.Descriptor instead.
func (*VideoSourceInfo) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{19}
}

func (x *VideoSourceInfo) GetType() VideoSourceType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return VideoSourceType_VIDEO_SOURCE_NATIVE
}

type OwnedVideoSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *FfiOwnedHandle        `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Info          *VideoSourceInfo       `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedVideoSource) Reset() {
	*x = OwnedVideoSource{}
	mi := &file_video_frame_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedVideoSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedVideoSource) ProtoMessage() {}

func (x *OwnedVideoSource) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedVideoSource.ProtoReflect.Descriptor instead.
func (*OwnedVideoSource) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{20}
}

func (x *OwnedVideoSource) GetHandle() *FfiOwnedHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *OwnedVideoSource) GetInfo() *VideoSourceInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type VideoBufferInfo_ComponentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPtr       *uint64                `protobuf:"varint,1,req,name=data_ptr,json=dataPtr" json:"data_ptr,omitempty"`
	Stride        *uint32                `protobuf:"varint,2,req,name=stride" json:"stride,omitempty"`
	Size          *uint32                `protobuf:"varint,3,req,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoBufferInfo_ComponentInfo) Reset() {
	*x = VideoBufferInfo_ComponentInfo{}
	mi := &file_video_frame_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoBufferInfo_ComponentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoBufferInfo_ComponentInfo) ProtoMessage() {}

func (x *VideoBufferInfo_ComponentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_frame_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoBufferInfo_ComponentInfo.ProtoReflect.Descriptor instead.
func (*VideoBufferInfo_ComponentInfo) Descriptor() ([]byte, []int) {
	return file_video_frame_proto_rawDescGZIP(), []int{11, 0}
}

func (x *VideoBufferInfo_ComponentInfo) GetDataPtr() uint64 {
	if x != nil && x.DataPtr != nil {
		return *x.DataPtr
	}
	return 0
}

func (x *VideoBufferInfo_ComponentInfo) GetStride() uint32 {
	if x != nil && x.Stride != nil {
		return *x.Stride
	}
	return 0
}

func (x *VideoBufferInfo_ComponentInfo) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

var File_video_frame_proto protoreflect.FileDescriptor

const file_video_frame_proto_rawDesc = "" +
	"\n" +
	"\x11video_frame.proto\x12\rlivekit.proto\x1a\fhandle.proto\x1a\vtrack.proto\"\xd1\x01\n" +
	"\x15NewVideoStreamRequest\x12!\n" +
	"\ftrack_handle\x18\x01 \x02(\x04R\vtrackHandle\x122\n" +
	"\x04type\x18\x02 \x02(\x0e2\x1e.livekit.proto.VideoStreamTypeR\x04type\x126\n" +
	"\x06format\x18\x03 \x01(\x0e2\x1e.livekit.proto.VideoBufferTypeR\x06format\x12)\n" +
	"\x10normalize_stride\x18\x04 \x01(\bR\x0fnormalizeStride\"Q\n" +
	"\x16NewVideoStreamResponse\x127\n" +
	"\x06stream\x18\x01 \x02(\v2\x1f.livekit.proto.OwnedVideoStreamR\x06stream\"\xa8\x02\n" +
	"!VideoStreamFromParticipantRequest\x12-\n" +
	"\x12participant_handle\x18\x01 \x02(\x04R\x11participantHandle\x122\n" +
	"\x04type\x18\x02 \x02(\x0e2\x1e.livekit.proto.VideoStreamTypeR\x04type\x12=\n" +
	"\ftrack_source\x18\x03 \x02(\x0e2\x1a.livekit.proto.TrackSourceR\vtrackSource\x126\n" +
	"\x06format\x18\x04 \x01(\x0e2\x1e.livekit.proto.VideoBufferTypeR\x06format\x12)\n" +
	"\x10normalize_stride\x18\x05 \x01(\bR\x0fnormalizeStride\"]\n" +
	"\"VideoStreamFromParticipantResponse\x127\n" +
	"\x06stream\x18\x01 \x02(\v2\x1f.livekit.proto.OwnedVideoStreamR\x06stream\"\x91\x01\n" +
	"\x15NewVideoSourceRequest\x122\n" +
	"\x04type\x18\x01 \x02(\x0e2\x1e.livekit.proto.VideoSourceTypeR\x04type\x12D\n" +
	"\n" +
	"resolution\x18\x02 \x02(\v2$.livekit.proto.VideoSourceResolutionR\n" +
	"resolution\"Q\n" +
	"\x16NewVideoSourceResponse\x127\n" +
	"\x06source\x18\x01 \x02(\v2\x1f.livekit.proto.OwnedVideoSourceR\x06source\"\xd4\x01\n" +
	"\x18CaptureVideoFrameRequest\x12#\n" +
	"\rsource_handle\x18\x01 \x02(\x04R\fsourceHandle\x126\n" +
	"\x06buffer\x18\x02 \x02(\v2\x1e.livekit.proto.VideoBufferInfoR\x06buffer\x12!\n" +
	"\ftimestamp_us\x18\x03 \x02(\x03R\vtimestampUs\x128\n" +
	"\brotation\x18\x04 \x02(\x0e2\x1c.livekit.proto.VideoRotationR\brotation\"\x1b\n" +
	"\x19CaptureVideoFrameResponse\"\x9f\x01\n" +
	"\x13VideoConvertRequest\x12\x15\n" +
	"\x06flip_y\x18\x01 \x01(\bR\x05flipY\x126\n" +
	"\x06buffer\x18\x02 \x02(\v2\x1e.livekit.proto.VideoBufferInfoR\x06buffer\x129\n" +
	"\bdst_type\x18\x03 \x02(\x0e2\x1e.livekit.proto.VideoBufferTypeR\adstType\"t\n" +
	"\x14VideoConvertResponse\x12\x16\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x129\n" +
	"\x06buffer\x18\x02 \x01(\v2\x1f.livekit.proto.OwnedVideoBufferH\x00R\x06bufferB\t\n" +
	"\amessage\"^\n" +
	"\x0fVideoResolution\x12\x14\n" +
	"\x05width\x18\x01 \x02(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x02(\rR\x06height\x12\x1d\n" +
	"\n" +
	"frame_rate\x18\x03 \x02(\x01R\tframeRate\"\xcc\x02\n" +
	"\x0fVideoBufferInfo\x122\n" +
	"\x04type\x18\x01 \x02(\x0e2\x1e.livekit.proto.VideoBufferTypeR\x04type\x12\x14\n" +
	"\x05width\x18\x02 \x02(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x02(\rR\x06height\x12\x19\n" +
	"\bdata_ptr\x18\x04 \x02(\x04R\adataPtr\x12\x16\n" +
	"\x06stride\x18\x06 \x01(\rR\x06stride\x12L\n" +
	"\n" +
	"components\x18\a \x03(\v2,.livekit.proto.VideoBufferInfo.ComponentInfoR\n" +
	"components\x1aV\n" +
	"\rComponentInfo\x12\x19\n" +
	"\bdata_ptr\x18\x01 \x02(\x04R\adataPtr\x12\x16\n" +
	"\x06stride\x18\x02 \x02(\rR\x06stride\x12\x12\n" +
	"\x04size\x18\x03 \x02(\rR\x04size\"}\n" +
	"\x10OwnedVideoBuffer\x125\n" +
	"\x06handle\x18\x01 \x02(\v2\x1d.livekit.proto.FfiOwnedHandleR\x06handle\x122\n" +
	"\x04info\x18\x02 \x02(\v2\x1e.livekit.proto.VideoBufferInfoR\x04info\"E\n" +
	"\x0fVideoStreamInfo\x122\n" +
	"\x04type\x18\x01 \x02(\x0e2\x1e.livekit.proto.VideoStreamTypeR\x04type\"}\n" +
	"\x10OwnedVideoStream\x125\n" +
	"\x06handle\x18\x01 \x02(\v2\x1d.livekit.proto.FfiOwnedHandleR\x06handle\x122\n" +
	"\x04info\x18\x02 \x02(\v2\x1e.livekit.proto.VideoStreamInfoR\x04info\"\xc1\x01\n" +
	"\x10VideoStreamEvent\x12#\n" +
	"\rstream_handle\x18\x01 \x02(\x04R\fstreamHandle\x12J\n" +
	"\x0eframe_received\x18\x02 \x01(\v2!.livekit.proto.VideoFrameReceivedH\x00R\rframeReceived\x121\n" +
	"\x03eos\x18\x03 \x01(\v2\x1d.livekit.proto.VideoStreamEOSH\x00R\x03eosB\t\n" +
	"\amessage\"\xaa\x01\n" +
	"\x12VideoFrameReceived\x127\n" +
	"\x06buffer\x18\x01 \x02(\v2\x1f.livekit.proto.OwnedVideoBufferR\x06buffer\x12!\n" +
	"\ftimestamp_us\x18\x02 \x02(\x03R\vtimestampUs\x128\n" +
	"\brotation\x18\x03 \x02(\x0e2\x1c.livekit.proto.VideoRotationR\brotation\"\x10\n" +
	"\x0eVideoStreamEOS\"E\n" +
	"\x15VideoSourceResolution\x12\x14\n" +
	"\x05width\x18\x01 \x02(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x02(\rR\x06height\"E\n" +
	"\x0fVideoSourceInfo\x122\n" +
	"\x04type\x18\x01 \x02(\x0e2\x1e.livekit.proto.VideoSourceTypeR\x04type\"}\n" +
	"\x10OwnedVideoSource\x125\n" +
	"\x06handle\x18\x01 \x02(\v2\x1d.livekit.proto.FfiOwnedHandleR\x06handle\x122\n" +
	"\x04info\x18\x02 \x02(\v2\x1e.livekit.proto.VideoSourceInfoR\x04info*1\n" +
	"\n" +
	"VideoCodec\x12\a\n" +
	"\x03VP8\x10\x00\x12\b\n" +
	"\x04H264\x10\x01\x12\a\n" +
	"\x03AV1\x10\x02\x12\a\n" +
	"\x03VP9\x10\x03*l\n" +
	"\rVideoRotation\x12\x14\n" +
	"\x10VIDEO_ROTATION_0\x10\x00\x12\x15\n" +
	"\x11VIDEO_ROTATION_90\x10\x01\x12\x16\n" +
	"\x12VIDEO_ROTATION_180\x10\x02\x12\x16\n" +
	"\x12VIDEO_ROTATION_270\x10\x03*\x81\x01\n" +
	"\x0fVideoBufferType\x12\b\n" +
	"\x04RGBA\x10\x00\x12\b\n" +
	"\x04ABGR\x10\x01\x12\b\n" +
	"\x04ARGB\x10\x02\x12\b\n" +
	"\x04BGRA\x10\x03\x12\t\n" +
	"\x05RGB24\x10\x04\x12\b\n" +
	"\x04I420\x10\x05\x12\t\n" +
	"\x05I420A\x10\x06\x12\b\n" +
	"\x04I422\x10\a\x12\b\n" +
	"\x04I444\x10\b\x12\b\n" +
	"\x04I010\x10\t\x12\b\n" +
	"\x04NV12\x10\n" +
	"*Y\n" +
	"\x0fVideoStreamType\x12\x17\n" +
	"\x13VIDEO_STREAM_NATIVE\x10\x00\x12\x16\n" +
	"\x12VIDEO_STREAM_WEBGL\x10\x01\x12\x15\n" +
	"\x11VIDEO_STREAM_HTML\x10\x02**\n" +
	"\x0fVideoSourceType\x12\x17\n" +
	"\x13VIDEO_SOURCE_NATIVE\x10\x00B\x19Z\a./proto\xaa\x02\rLiveKit.Proto"

var (
	file_video_frame_proto_rawDescOnce sync.Once
	file_video_frame_proto_rawDescData []byte
)

func file_video_frame_proto_rawDescGZIP() []byte {
	file_video_frame_proto_rawDescOnce.Do(func() {
		file_video_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_frame_proto_rawDesc), len(file_video_frame_proto_rawDesc)))
	})
	return file_video_frame_proto_rawDescData
}

var file_video_frame_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_video_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_video_frame_proto_goTypes = []any{
	(VideoCodec)(0),                            // 0: livekit.proto.VideoCodec
	(VideoRotation)(0),                         // 1: livekit.proto.VideoRotation
	(VideoBufferType)(0),                       // 2: livekit.proto.VideoBufferType
	(VideoStreamType)(0),                       // 3: livekit.proto.VideoStreamType
	(VideoSourceType)(0),                       // 4: livekit.proto.VideoSourceType
	(*NewVideoStreamRequest)(nil),              // 5: livekit.proto.NewVideoStreamRequest
	(*NewVideoStreamResponse)(nil),             // 6: livekit.proto.NewVideoStreamResponse
	(*VideoStreamFromParticipantRequest)(nil),  // 7: livekit.proto.VideoStreamFromParticipantRequest
	(*VideoStreamFromParticipantResponse)(nil), // 8: livekit.proto.VideoStreamFromParticipantResponse
	(*NewVideoSourceRequest)(nil),              // 9: livekit.proto.NewVideoSourceRequest
	(*NewVideoSourceResponse)(nil),             // 10: livekit.proto.NewVideoSourceResponse
	(*CaptureVideoFrameRequest)(nil),           // 11: livekit.proto.CaptureVideoFrameRequest
	(*CaptureVideoFrameResponse)(nil),          // 12: livekit.proto.CaptureVideoFrameResponse
	(*VideoConvertRequest)(nil),                // 13: livekit.proto.VideoConvertRequest
	(*VideoConvertResponse)(nil),               // 14: livekit.proto.VideoConvertResponse
	(*VideoResolution)(nil),                    // 15: livekit.proto.VideoResolution
	(*VideoBufferInfo)(nil),                    // 16: livekit.proto.VideoBufferInfo
	(*OwnedVideoBuffer)(nil),                   // 17: livekit.proto.OwnedVideoBuffer
	(*VideoStreamInfo)(nil),                    // 18: livekit.proto.VideoStreamInfo
	(*OwnedVideoStream)(nil),                   // 19: livekit.proto.OwnedVideoStream
	(*VideoStreamEvent)(nil),                   // 20: livekit.proto.VideoStreamEvent
	(*VideoFrameReceived)(nil),                 // 21: livekit.proto.VideoFrameReceived
	(*VideoStreamEOS)(nil),                     // 22: livekit.proto.VideoStreamEOS
	(*VideoSourceResolution)(nil),              // 23: livekit.proto.VideoSourceResolution
	(*VideoSourceInfo)(nil),                    // 24: livekit.proto.VideoSourceInfo
	(*OwnedVideoSource)(nil),                   // 25: livekit.proto.OwnedVideoSource
	(*VideoBufferInfo_ComponentInfo)(nil),      // 26: livekit.proto.VideoBufferInfo.ComponentInfo
	(TrackSource)(0),                           // 27: livekit.proto.TrackSource
	(*FfiOwnedHandle)(nil),                     // 28: livekit.proto.FfiOwnedHandle
}
var file_video_frame_proto_depIdxs = []int32{
	3,  // 0: livekit.proto.NewVideoStreamRequest.type:type_name -> livekit.proto.VideoStreamType
	2,  // 1: livekit.proto.NewVideoStreamRequest.format:type_name -> livekit.proto.VideoBufferType
	19, // 2: livekit.proto.NewVideoStreamResponse.stream:type_name -> livekit.proto.OwnedVideoStream
	3,  // 3: livekit.proto.VideoStreamFromParticipantRequest.type:type_name -> livekit.proto.VideoStreamType
	27, // 4: livekit.proto.VideoStreamFromParticipantRequest.track_source:type_name -> livekit.proto.TrackSource
	2,  // 5: livekit.proto.VideoStreamFromParticipantRequest.format:type_name -> livekit.proto.VideoBufferType
	19, // 6: livekit.proto.VideoStreamFromParticipantResponse.stream:type_name -> livekit.proto.OwnedVideoStream
	4,  // 7: livekit.proto.NewVideoSourceRequest.type:type_name -> livekit.proto.VideoSourceType
	23, // 8: livekit.proto.NewVideoSourceRequest.resolution:type_name -> livekit.proto.VideoSourceResolution
	25, // 9: livekit.proto.NewVideoSourceResponse.source:type_name -> livekit.proto.OwnedVideoSource
	16, // 10: livekit.proto.CaptureVideoFrameRequest.buffer:type_name -> livekit.proto.VideoBufferInfo
	1,  // 11: livekit.proto.CaptureVideoFrameRequest.rotation:type_name -> livekit.proto.VideoRotation
	16, // 12: livekit.proto.VideoConvertRequest.buffer:type_name -> livekit.proto.VideoBufferInfo
	2,  // 13: livekit.proto.VideoConvertRequest.dst_type:type_name -> livekit.proto.VideoBufferType
	17, // 14: livekit.proto.VideoConvertResponse.buffer:type_name -> livekit.proto.OwnedVideoBuffer
	2,  // 15: livekit.proto.VideoBufferInfo.type:type_name -> livekit.proto.VideoBufferType
	26, // 16: livekit.proto.VideoBufferInfo.components:type_name -> livekit.proto.VideoBufferInfo.ComponentInfo
	28, // 17: livekit.proto.OwnedVideoBuffer.handle:type_name -> livekit.proto.FfiOwnedHandle
	16, // 18: livekit.proto.OwnedVideoBuffer.info:type_name -> livekit.proto.VideoBufferInfo
	3,  // 19: livekit.proto.VideoStreamInfo.type:type_name -> livekit.proto.VideoStreamType
	28, // 20: livekit.proto.OwnedVideoStream.handle:type_name -> livekit.proto.FfiOwnedHandle
	18, // 21: livekit.proto.OwnedVideoStream.info:type_name -> livekit.proto.VideoStreamInfo
	21, // 22: livekit.proto.VideoStreamEvent.frame_received:type_name -> livekit.proto.VideoFrameReceived
	22, // 23: livekit.proto.VideoStreamEvent.eos:type_name -> livekit.proto.VideoStreamEOS
	17, // 24: livekit.proto.VideoFrameReceived.buffer:type_name -> livekit.proto.OwnedVideoBuffer
	1,  // 25: livekit.proto.VideoFrameReceived.rotation:type_name -> livekit.proto.VideoRotation
	4,  // 26: livekit.proto.VideoSourceInfo.type:type_name -> livekit.proto.VideoSourceType
	28, // 27: livekit.proto.OwnedVideoSource.handle:type_name -> livekit.proto.FfiOwnedHandle
	24, // 28: livekit.proto.OwnedVideoSource.info:type_name -> livekit.proto.VideoSourceInfo
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_video_frame_proto_init() }
func file_video_frame_proto_init() {
	if File_video_frame_proto != nil {
		return
	}
	file_handle_proto_init()
	file_track_proto_init()
	file_video_frame_proto_msgTypes[9].OneofWrappers = []any{
		(*VideoConvertResponse_Error)(nil),
		(*VideoConvertResponse_Buffer)(nil),
	}
	file_video_frame_proto_msgTypes[15].OneofWrappers = []any{
		(*VideoStreamEvent_FrameReceived)(nil),
		(*VideoStreamEvent_Eos)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_frame_proto_rawDesc), len(file_video_frame_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_video_frame_proto_goTypes,
		DependencyIndexes: file_video_frame_proto_depIdxs,
		EnumInfos:         file_video_frame_proto_enumTypes,
		MessageInfos:      file_video_frame_proto_msgTypes,
	}.Build()
	File_video_frame_proto = out.File
	file_video_frame_proto_goTypes = nil
	file_video_frame_proto_depIdxs = nil
}
